/**
 * Seed Data Generator Configuration
 *
 * This configuration controls all aspects of the generated seed data.
 * All values are deterministic - running the generator multiple times
 * produces identical output.
 */

export const SEED_CONFIG = {
  // Random seed for deterministic generation
  // Changing this will produce entirely different (but still consistent) data
  RANDOM_SEED: "trainers-gg-seed-2026",

  // Password for all test users (meets Supabase Auth requirements)
  DEFAULT_PASSWORD: "Password123!",

  // =========================================================================
  // User Configuration
  // =========================================================================

  // User data is loaded from data/users.json (generated by generate-user-data.ts)
  // Run `pnpm generate-seed-json` to create/update the JSON file

  // User counts (for reference - actual counts are in users.json)
  STAFF_USERS_COUNT: 25,
  PLAYER_USERS_COUNT: 320,

  // Alt distribution per user
  MIN_ALTS_PER_USER: 2,
  MAX_ALTS_PER_USER: 5,

  // =========================================================================
  // Organization Configuration
  // =========================================================================

  ORGANIZATIONS: [
    {
      slug: "vgc-league",
      name: "VGC League",
      ownerUsername: "admin_trainer",
      mainDay: 6, // Saturday (0 = Sunday, 6 = Saturday)
      practiceDay: 2, // Tuesday
      tier: "partner" as const,
      subscriptionTier: "organization_plus" as const,
      existing: true,
    },
    {
      slug: "pallet-town",
      name: "Pallet Town Trainers",
      ownerUsername: "ash_ketchum",
      mainDay: 0, // Sunday
      practiceDay: 1, // Monday
      tier: "regular" as const,
      subscriptionTier: "free" as const,
      existing: true,
    },
    {
      slug: "sinnoh-champions",
      name: "Sinnoh Champions",
      ownerUsername: "cynthia",
      mainDay: 5, // Friday
      practiceDay: 3, // Wednesday
      tier: "verified" as const,
      subscriptionTier: "organization_plus" as const,
      existing: true,
    },
    {
      slug: "kanto-elite",
      name: "Kanto Elite Series",
      ownerUsername: "admin_trainer", // admin owns 2 orgs
      mainDay: 4, // Thursday
      practiceDay: 1, // Monday
      tier: "verified" as const,
      subscriptionTier: "organization_plus" as const,
      existing: false,
    },
    {
      slug: "johto-masters",
      name: "Johto Masters League",
      ownerUsername: "lance", // new user
      mainDay: 3, // Wednesday
      practiceDay: 2, // Tuesday
      tier: "verified" as const,
      subscriptionTier: "organization_plus" as const,
      existing: false,
    },
  ],

  // Staff overlap configuration
  // Percentage of staff who work for multiple orgs
  STAFF_MULTI_ORG_RATE: 0.3, // 30% work for 2 orgs
  STAFF_THREE_ORG_RATE: 0.1, // 10% work for 3 orgs

  // =========================================================================
  // Tournament Configuration
  // =========================================================================

  // Tournament timeline (relative to current date at seed time)
  // Past tournaments have matches, results, and standings
  // Future tournaments have registrations but no matches yet
  WEEKS_OF_PAST_TOURNAMENTS: 10,
  WEEKS_OF_FUTURE_TOURNAMENTS: 1,

  // Each org runs 2 tournaments per week (main + practice)
  TOURNAMENTS_PER_WEEK_PER_ORG: 2,

  // Flagship tournament configuration (256 players)
  FLAGSHIP_TOURNAMENT_SIZE: 256,
  FLAGSHIP_TOURNAMENTS: [
    { orgSlug: "vgc-league", week: 6, name: "VGC League Championship" },
    { orgSlug: "sinnoh-champions", week: 10, name: "Sinnoh Grand Finals" },
    {
      orgSlug: "pallet-town",
      week: 11,
      name: "Pallet Town Trainers Week 11 Championship",
      active: true,
    },
    {
      orgSlug: "kanto-elite",
      week: 11,
      name: "Kanto Elite Series Week 11 Championship",
      active: true,
    },
  ],

  // Main tournament size distribution (excluding flagships)
  MAIN_TOURNAMENT_SIZES: [
    { size: 128, weight: 0.2 }, // 20% are 128 players
    { size: 64, weight: 0.5 }, // 50% are 64 players
    { size: 32, weight: 0.3 }, // 30% are 32 players
  ],

  // Practice tournament configuration
  PRACTICE_TOURNAMENT_SIZES: [16, 24, 32],
  PRACTICE_FORMATS: [
    { format: "swiss_only" as const, weight: 0.67 },
    { format: "single_elimination" as const, weight: 0.17 },
    { format: "double_elimination" as const, weight: 0.16 },
  ],

  // Swiss rounds by player count
  SWISS_ROUNDS: {
    256: 8,
    128: 7,
    64: 6,
    32: 5,
    24: 5,
    16: 4,
  } as Record<number, number>,

  // Top cut sizes by player count
  TOP_CUT_SIZES: {
    256: 8,
    128: 8,
    64: 8,
    32: 4,
  } as Record<number, number>,

  // =========================================================================
  // Match Configuration
  // =========================================================================

  // Score distribution (Best of 3)
  // No ties in VGC/Pokemon GO - always a clear winner
  SCORE_2_0_RATE: 0.6, // 60% of matches are 2-0
  SCORE_2_1_RATE: 0.4, // 40% of matches are 2-1

  // Round time in minutes
  ROUND_TIME_MINUTES: 50,

  // =========================================================================
  // Role Configuration
  // =========================================================================

  ROLES: {
    SITE_ADMIN: "Site Admin",
    ORG_OWNER: "org_owner",
    ORG_ADMIN: "org_admin",
    ORG_MODERATOR: "org_moderator",
    ORG_TOURNAMENT_ORGANIZER: "org_tournament_organizer",
    ORG_JUDGE: "org_judge",
  },

  // Staff roles to assign per organization
  STAFF_ROLES_PER_ORG: [
    { role: "org_admin", count: 1 },
    { role: "org_judge", count: 5 }, // 2 head + 3 regular
    { role: "org_moderator", count: 2 },
    { role: "org_tournament_organizer", count: 2 },
  ],
} as const;

// Type exports for use in generators
export type OrganizationConfig = (typeof SEED_CONFIG.ORGANIZATIONS)[number];
export type TournamentFormat =
  | "swiss_only"
  | "swiss_with_cut"
  | "single_elimination"
  | "double_elimination";
export type PhaseType = "swiss" | "single_elimination" | "double_elimination";
