web:
  - changed-files:
      - any-glob-to-any-file: ["apps/web/**"]

mobile:
  - changed-files:
      - any-glob-to-any-file: ["apps/mobile/**"]

supabase:
  - changed-files:
      - any-glob-to-any-file: ["packages/supabase/**"]

validators:
  - changed-files:
      - any-glob-to-any-file: ["packages/validators/**"]

atproto:
  - changed-files:
      - any-glob-to-any-file: ["packages/atproto/**"]

ui:
  - changed-files:
      - any-glob-to-any-file: ["packages/ui/**"]

theme:
  - changed-files:
      - any-glob-to-any-file: ["packages/theme/**"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]

migrations:
  - changed-files:
      - any-glob-to-any-file: ["packages/supabase/supabase/migrations/**"]

infrastructure:
  - changed-files:
      - any-glob-to-any-file: ["infra/**"]

tooling:
  - changed-files:
      - any-glob-to-any-file: ["tooling/**"]

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "pnpm-lock.yaml"
          - "pnpm-workspace.yaml"
