packages:
  - apps/*
  - packages/*
  - tooling/*
  - infra/*

catalog:
  "@atproto/api": ^0.18.17
  "@atproto/jwk-jose": ^0.1.11
  "@pkmn/data": ^0.10.5
  "@pkmn/dex": ^0.10.5
  "@pkmn/img": ^0.3.3
  "@pkmn/sets": ^5.2.0
  "@pkmn/sim": ^0.10.5
  "@supabase/ssr": ^0.8.0
  "@supabase/supabase-js": ^2.91.0
  "@tanstack/react-query": ^5.90.19
  "@types/node": ^22.19.7
  "@types/react": ~19.1.10
  "@types/react-dom": ~19.1.0
  babel-plugin-react-compiler: ^1.0.0
  "@types/jest": ^29.5.14
  eslint: ^9.39.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
  jest: ^29.7.0
  jest-junit: ^16.0.0
  jose: ^5.10.0
  next: ^16
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  supabase: ^2.75.3
  tailwindcss: ^4.0.0
  ts-jest: ^29.4.6
  tsx: ^4.21.0
  typescript: ^5.9.3
  zod: ^3.25.76

onlyBuiltDependencies:
  - "@clerk/shared"
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - msw
  - sharp
  - supabase
  - utf-8-validate
