packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@supabase/ssr": ^0.8.0
  "@supabase/supabase-js": ^2.91.0
  "@types/node": ^22.19.7
  "@types/react": ~19.1.10
  "@types/react-dom": ~19.1.0
  eslint: ^9.39.2
  prettier: ^3.8.1
  react: 19.1.0
  react-dom: 19.1.0
  typescript: ^5.9.3
  zod: ^3.25.76

onlyBuiltDependencies:
  - "@clerk/shared"
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - msw
  - sharp
  - supabase
  - utf-8-validate
