packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - "@clerk/shared"
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - msw
  - sharp
  - supabase
  - utf-8-validate
