/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: pnpm --filter @trainers/supabase generate-clients
 *
 * Browser Client Wrapper (Next.js Client Components)
 *
 * All queries and mutations auto-injected with Next.js browser Supabase client.
 * This eliminates the need for a service layer - just import from @trainers/supabase/client.
 */

import { createBrowserSupabaseClient } from "./base/browser-client";
import { getTournamentAuditLog as getTournamentAuditLog_core } from "../queries/audit-log";
import { getMatchAuditLog as getMatchAuditLog_core } from "../queries/audit-log";
import { getMatchGames as getMatchGames_core } from "../queries/match-games";
import { getMatchGamesForPlayer as getMatchGamesForPlayer_core } from "../queries/match-games";
import { getMatchMessages as getMatchMessages_core } from "../queries/match-games";
import { getMatchGame as getMatchGame_core } from "../queries/match-games";
import { getNotifications as getNotifications_core } from "../queries/notifications";
import { getUnreadNotificationCount as getUnreadNotificationCount_core } from "../queries/notifications";
import { getActiveMatchNotifications as getActiveMatchNotifications_core } from "../queries/notifications";
import { listPublicOrganizations as listPublicOrganizations_core } from "../queries/organizations";
import { listOrganizations as listOrganizations_core } from "../queries/organizations";
import { getOrganizationBySlug as getOrganizationBySlug_core } from "../queries/organizations";
import { getOrganizationById as getOrganizationById_core } from "../queries/organizations";
import { listMyOrganizations as listMyOrganizations_core } from "../queries/organizations";
import { canManageOrganization as canManageOrganization_core } from "../queries/organizations";
import { listOrganizationStaff as listOrganizationStaff_core } from "../queries/organizations";
import { hasOrganizationAccess as hasOrganizationAccess_core } from "../queries/organizations";
import { getMyOrganizationInvitations as getMyOrganizationInvitations_core } from "../queries/organizations";
import { getOrganizationInvitations as getOrganizationInvitations_core } from "../queries/organizations";
import { listMyOwnedOrganizations as listMyOwnedOrganizations_core } from "../queries/organizations";
import { getOrganizationWithTournamentStats as getOrganizationWithTournamentStats_core } from "../queries/organizations";
import { listOrganizationTournaments as listOrganizationTournaments_core } from "../queries/organizations";
import { listOrganizationStaffWithRoles as listOrganizationStaffWithRoles_core } from "../queries/organizations";
import { listOrganizationGroups as listOrganizationGroups_core } from "../queries/organizations";
import { searchUsersForInvite as searchUsersForInvite_core } from "../queries/organizations";
import { hasOrgPermission as hasOrgPermission_core } from "../queries/organizations";
import { getUserPermissions as getUserPermissions_core } from "../queries/permissions";
import { hasPermission as hasPermission_core } from "../queries/permissions";
import { getFeedPosts as getFeedPosts_core } from "../queries/posts";
import { getFollowingFeedPosts as getFollowingFeedPosts_core } from "../queries/posts";
import { getPostWithReplies as getPostWithReplies_core } from "../queries/posts";
import { getUserPosts as getUserPosts_core } from "../queries/posts";
import { isSiteAdmin as isSiteAdmin_core } from "../queries/site-roles";
import { getSiteRoles as getSiteRoles_core } from "../queries/site-roles";
import { getSiteAdmins as getSiteAdmins_core } from "../queries/site-roles";
import { getUserSiteRoles as getUserSiteRoles_core } from "../queries/site-roles";
import { grantSiteRole as grantSiteRole_core } from "../queries/site-roles";
import { revokeSiteRole as revokeSiteRole_core } from "../queries/site-roles";
import { getActiveSudoSession as getActiveSudoSession_core } from "../queries/sudo-mode";
import { isSudoModeActive as isSudoModeActive_core } from "../queries/sudo-mode";
import { getSudoSessions as getSudoSessions_core } from "../queries/sudo-mode";
import { startSudoSession as startSudoSession_core } from "../queries/sudo-mode";
import { endSudoSession as endSudoSession_core } from "../queries/sudo-mode";
import { listTournamentsGrouped as listTournamentsGrouped_core } from "../queries/tournaments";
import { listPublicTournaments as listPublicTournaments_core } from "../queries/tournaments";
import { listTournaments as listTournaments_core } from "../queries/tournaments";
import { getTournamentByOrgAndSlug as getTournamentByOrgAndSlug_core } from "../queries/tournaments";
import { checkTournamentSlugAvailable as checkTournamentSlugAvailable_core } from "../queries/tournaments";
import { getTournamentBySlug as getTournamentBySlug_core } from "../queries/tournaments";
import { getTournamentById as getTournamentById_core } from "../queries/tournaments";
import { getTournamentRegistrations as getTournamentRegistrations_core } from "../queries/tournaments";
import { isRegisteredForTournament as isRegisteredForTournament_core } from "../queries/tournaments";
import { getCurrentUserRegisteredTournamentIds as getCurrentUserRegisteredTournamentIds_core } from "../queries/tournaments";
import { getUserRegistrationDetails as getUserRegistrationDetails_core } from "../queries/tournaments";
import { getTournamentPhases as getTournamentPhases_core } from "../queries/tournaments";
import { getTournamentRounds as getTournamentRounds_core } from "../queries/tournaments";
import { getRoundMatches as getRoundMatches_core } from "../queries/tournaments";
import { getTournamentStandings as getTournamentStandings_core } from "../queries/tournaments";
import { getPlayerTournamentStats as getPlayerTournamentStats_core } from "../queries/tournaments";
import { getTournamentPlayerStats as getTournamentPlayerStats_core } from "../queries/tournaments";
import { getPhaseRoundsWithStats as getPhaseRoundsWithStats_core } from "../queries/tournaments";
import { getRoundMatchesWithStats as getRoundMatchesWithStats_core } from "../queries/tournaments";
import { getPhaseRoundsWithMatches as getPhaseRoundsWithMatches_core } from "../queries/tournaments";
import { getCheckInStatus as getCheckInStatus_core } from "../queries/tournaments";
import { getCheckInStats as getCheckInStats_core } from "../queries/tournaments";
import { getUserTeams as getUserTeams_core } from "../queries/tournaments";
import { getMatchDetails as getMatchDetails_core } from "../queries/tournaments";
import { getPlayerMatches as getPlayerMatches_core } from "../queries/tournaments";
import { getTournamentMatchesForStaff as getTournamentMatchesForStaff_core } from "../queries/tournaments";
import { getMyDashboardData as getMyDashboardData_core } from "../queries/tournaments";
import { getRegistrationStatus as getRegistrationStatus_core } from "../queries/tournaments";
import { getTournamentInvitationsSent as getTournamentInvitationsSent_core } from "../queries/tournaments";
import { getTournamentInvitationsReceived as getTournamentInvitationsReceived_core } from "../queries/tournaments";
import { getTeamForRegistration as getTeamForRegistration_core } from "../queries/tournaments";
import { getUnpairedCheckedInPlayers as getUnpairedCheckedInPlayers_core } from "../queries/tournaments";
import { getUserTournamentHistory as getUserTournamentHistory_core } from "../queries/tournaments";
import { getUserCount as getUserCount_core } from "../queries/users";
import { getCurrentUser as getCurrentUser_core } from "../queries/users";
import { getUserSpritePreference as getUserSpritePreference_core } from "../queries/users";
import { getUserById as getUserById_core } from "../queries/users";
import { getUserWithAlt as getUserWithAlt_core } from "../queries/users";
import { getAltByUsername as getAltByUsername_core } from "../queries/users";
import { getAltByUserId as getAltByUserId_core } from "../queries/users";
import { getAltsByUserId as getAltsByUserId_core } from "../queries/users";
import { getCurrentUserAlts as getCurrentUserAlts_core } from "../queries/users";
import { searchAlts as searchAlts_core } from "../queries/users";
import { getEmailByUsername as getEmailByUsername_core } from "../queries/users";
import { submitGameSelection as submitGameSelection_core } from "../mutations/match-games";
import { sendMatchMessage as sendMatchMessage_core } from "../mutations/match-games";
import { sendSystemMessage as sendSystemMessage_core } from "../mutations/match-games";
import { createMatchGames as createMatchGames_core } from "../mutations/match-games";
import { judgeOverrideGame as judgeOverrideGame_core } from "../mutations/match-games";
import { judgeResetGame as judgeResetGame_core } from "../mutations/match-games";
import { resetMatch as resetMatch_core } from "../mutations/match-games";
import { markNotificationRead as markNotificationRead_core } from "../mutations/notifications";
import { markAllNotificationsRead as markAllNotificationsRead_core } from "../mutations/notifications";
import { deleteNotification as deleteNotification_core } from "../mutations/notifications";
import { createOrganization as createOrganization_core } from "../mutations/organizations";
import { updateOrganization as updateOrganization_core } from "../mutations/organizations";
import { inviteToOrganization as inviteToOrganization_core } from "../mutations/organizations";
import { acceptOrganizationInvitation as acceptOrganizationInvitation_core } from "../mutations/organizations";
import { declineOrganizationInvitation as declineOrganizationInvitation_core } from "../mutations/organizations";
import { leaveOrganization as leaveOrganization_core } from "../mutations/organizations";
import { removeStaff as removeStaff_core } from "../mutations/organizations";
import { addStaffMember as addStaffMember_core } from "../mutations/organizations";
import { addStaffToGroup as addStaffToGroup_core } from "../mutations/organizations";
import { removeStaffFromGroup as removeStaffFromGroup_core } from "../mutations/organizations";
import { changeStaffRole as changeStaffRole_core } from "../mutations/organizations";
import { removeStaffCompletely as removeStaffCompletely_core } from "../mutations/organizations";
import { updateAlt as updateAlt_core } from "../mutations/users";
import { updateUsername as updateUsername_core } from "../mutations/users";
import { ensureAlt as ensureAlt_core } from "../mutations/users";
import { createAlt as createAlt_core } from "../mutations/users";
import { deleteAlt as deleteAlt_core } from "../mutations/users";
import { setMainAlt as setMainAlt_core } from "../mutations/users";
import { startMatch as startMatch_core } from "../mutations/tournaments/matches";
import { reportMatchResult as reportMatchResult_core } from "../mutations/tournaments/matches";
import { updatePhase as updatePhase_core } from "../mutations/tournaments/phases";
import { createPhase as createPhase_core } from "../mutations/tournaments/phases";
import { deletePhase as deletePhase_core } from "../mutations/tournaments/phases";
import { saveTournamentPhases as saveTournamentPhases_core } from "../mutations/tournaments/phases";
import { registerForTournament as registerForTournament_core } from "../mutations/tournaments/registration";
import { updateRegistrationPreferences as updateRegistrationPreferences_core } from "../mutations/tournaments/registration";
import { cancelRegistration as cancelRegistration_core } from "../mutations/tournaments/registration";
import { updateRegistrationStatus as updateRegistrationStatus_core } from "../mutations/tournaments/registration";
import { checkIn as checkIn_core } from "../mutations/tournaments/registration";
import { undoCheckIn as undoCheckIn_core } from "../mutations/tournaments/registration";
import { withdrawFromTournament as withdrawFromTournament_core } from "../mutations/tournaments/registration";
import { sendTournamentInvitations as sendTournamentInvitations_core } from "../mutations/tournaments/registration";
import { respondToTournamentInvitation as respondToTournamentInvitation_core } from "../mutations/tournaments/registration";
import { generateRoundPairings as generateRoundPairings_core } from "../mutations/tournaments/rounds";
import { startRound as startRound_core } from "../mutations/tournaments/rounds";
import { completeRound as completeRound_core } from "../mutations/tournaments/rounds";
import { createRound as createRound_core } from "../mutations/tournaments/rounds";
import { deleteRoundAndMatches as deleteRoundAndMatches_core } from "../mutations/tournaments/rounds";
import { recalculateStandings as recalculateStandings_core } from "../mutations/tournaments/standings";
import { dropPlayer as dropPlayer_core } from "../mutations/tournaments/standings";
import { submitTeam as submitTeam_core } from "../mutations/tournaments/teams";
import { selectTeamForTournament as selectTeamForTournament_core } from "../mutations/tournaments/teams";
import { createTournament as createTournament_core } from "../mutations/tournaments/tournament-crud";
import { updateTournament as updateTournament_core } from "../mutations/tournaments/tournament-crud";
import { archiveTournament as archiveTournament_core } from "../mutations/tournaments/tournament-crud";
import { deleteTournament as deleteTournament_core } from "../mutations/tournaments/tournament-crud";
import { startTournamentEnhanced as startTournamentEnhanced_core } from "../mutations/tournaments/tournament-flow";
import { advanceToTopCut as advanceToTopCut_core } from "../mutations/tournaments/tournament-flow";
import { generateEliminationPairings as generateEliminationPairings_core } from "../mutations/tournaments/tournament-flow";
import { completeTournament as completeTournament_core } from "../mutations/tournaments/tournament-flow";

/**
 * getTournamentAuditLog (auto-injected with browser client)
 */
export async function getTournamentAuditLog(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentAuditLog_core(client, ...args);
}

/**
 * getMatchAuditLog (auto-injected with browser client)
 */
export async function getMatchAuditLog(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchAuditLog_core(client, ...args);
}

/**
 * getMatchGames (auto-injected with browser client)
 */
export async function getMatchGames(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchGames_core(client, ...args);
}

/**
 * getMatchGamesForPlayer (auto-injected with browser client)
 */
export async function getMatchGamesForPlayer(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchGamesForPlayer_core(client, ...args);
}

/**
 * getMatchMessages (auto-injected with browser client)
 */
export async function getMatchMessages(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchMessages_core(client, ...args);
}

/**
 * getMatchGame (auto-injected with browser client)
 */
export async function getMatchGame(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchGame_core(client, ...args);
}

/**
 * getNotifications (auto-injected with browser client)
 */
export async function getNotifications(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getNotifications_core(client, ...args);
}

/**
 * getUnreadNotificationCount (auto-injected with browser client)
 */
export async function getUnreadNotificationCount(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUnreadNotificationCount_core(client, ...args);
}

/**
 * getActiveMatchNotifications (auto-injected with browser client)
 */
export async function getActiveMatchNotifications(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getActiveMatchNotifications_core(client, ...args);
}

/**
 * listPublicOrganizations (auto-injected with browser client)
 */
export async function listPublicOrganizations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listPublicOrganizations_core(client, ...args);
}

/**
 * listOrganizations (auto-injected with browser client)
 */
export async function listOrganizations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listOrganizations_core(client, ...args);
}

/**
 * getOrganizationBySlug (auto-injected with browser client)
 */
export async function getOrganizationBySlug(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getOrganizationBySlug_core(client, ...args);
}

/**
 * getOrganizationById (auto-injected with browser client)
 */
export async function getOrganizationById(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getOrganizationById_core(client, ...args);
}

/**
 * listMyOrganizations (auto-injected with browser client)
 */
export async function listMyOrganizations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listMyOrganizations_core(client, ...args);
}

/**
 * canManageOrganization (auto-injected with browser client)
 */
export async function canManageOrganization(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return canManageOrganization_core(client, ...args);
}

/**
 * listOrganizationStaff (auto-injected with browser client)
 */
export async function listOrganizationStaff(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listOrganizationStaff_core(client, ...args);
}

/**
 * hasOrganizationAccess (auto-injected with browser client)
 */
export async function hasOrganizationAccess(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return hasOrganizationAccess_core(client, ...args);
}

/**
 * getMyOrganizationInvitations (auto-injected with browser client)
 */
export async function getMyOrganizationInvitations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMyOrganizationInvitations_core(client, ...args);
}

/**
 * getOrganizationInvitations (auto-injected with browser client)
 */
export async function getOrganizationInvitations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getOrganizationInvitations_core(client, ...args);
}

/**
 * listMyOwnedOrganizations (auto-injected with browser client)
 */
export async function listMyOwnedOrganizations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listMyOwnedOrganizations_core(client, ...args);
}

/**
 * getOrganizationWithTournamentStats (auto-injected with browser client)
 */
export async function getOrganizationWithTournamentStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getOrganizationWithTournamentStats_core(client, ...args);
}

/**
 * listOrganizationTournaments (auto-injected with browser client)
 */
export async function listOrganizationTournaments(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listOrganizationTournaments_core(client, ...args);
}

/**
 * listOrganizationStaffWithRoles (auto-injected with browser client)
 */
export async function listOrganizationStaffWithRoles(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listOrganizationStaffWithRoles_core(client, ...args);
}

/**
 * listOrganizationGroups (auto-injected with browser client)
 */
export async function listOrganizationGroups(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listOrganizationGroups_core(client, ...args);
}

/**
 * searchUsersForInvite (auto-injected with browser client)
 */
export async function searchUsersForInvite(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return searchUsersForInvite_core(client, ...args);
}

/**
 * hasOrgPermission (auto-injected with browser client)
 */
export async function hasOrgPermission(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return hasOrgPermission_core(client, ...args);
}

/**
 * getUserPermissions (auto-injected with browser client)
 */
export async function getUserPermissions(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserPermissions_core(client, ...args);
}

/**
 * hasPermission (auto-injected with browser client)
 */
export async function hasPermission(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return hasPermission_core(client, ...args);
}

/**
 * getFeedPosts (auto-injected with browser client)
 */
export async function getFeedPosts(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getFeedPosts_core(client, ...args);
}

/**
 * getFollowingFeedPosts (auto-injected with browser client)
 */
export async function getFollowingFeedPosts(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getFollowingFeedPosts_core(client, ...args);
}

/**
 * getPostWithReplies (auto-injected with browser client)
 */
export async function getPostWithReplies(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getPostWithReplies_core(client, ...args);
}

/**
 * getUserPosts (auto-injected with browser client)
 */
export async function getUserPosts(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserPosts_core(client, ...args);
}

/**
 * isSiteAdmin (auto-injected with browser client)
 */
export async function isSiteAdmin(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return isSiteAdmin_core(client, ...args);
}

/**
 * getSiteRoles (auto-injected with browser client)
 */
export async function getSiteRoles(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getSiteRoles_core(client, ...args);
}

/**
 * getSiteAdmins (auto-injected with browser client)
 */
export async function getSiteAdmins(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getSiteAdmins_core(client, ...args);
}

/**
 * getUserSiteRoles (auto-injected with browser client)
 */
export async function getUserSiteRoles(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserSiteRoles_core(client, ...args);
}

/**
 * grantSiteRole (auto-injected with browser client)
 */
export async function grantSiteRole(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return grantSiteRole_core(client, ...args);
}

/**
 * revokeSiteRole (auto-injected with browser client)
 */
export async function revokeSiteRole(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return revokeSiteRole_core(client, ...args);
}

/**
 * getActiveSudoSession (auto-injected with browser client)
 */
export async function getActiveSudoSession(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getActiveSudoSession_core(client, ...args);
}

/**
 * isSudoModeActive (auto-injected with browser client)
 */
export async function isSudoModeActive(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return isSudoModeActive_core(client, ...args);
}

/**
 * getSudoSessions (auto-injected with browser client)
 */
export async function getSudoSessions(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getSudoSessions_core(client, ...args);
}

/**
 * startSudoSession (auto-injected with browser client)
 */
export async function startSudoSession(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return startSudoSession_core(client, ...args);
}

/**
 * endSudoSession (auto-injected with browser client)
 */
export async function endSudoSession(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return endSudoSession_core(client, ...args);
}

/**
 * listTournamentsGrouped (auto-injected with browser client)
 */
export async function listTournamentsGrouped(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listTournamentsGrouped_core(client, ...args);
}

/**
 * listPublicTournaments (auto-injected with browser client)
 */
export async function listPublicTournaments(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listPublicTournaments_core(client, ...args);
}

/**
 * listTournaments (auto-injected with browser client)
 */
export async function listTournaments(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return listTournaments_core(client, ...args);
}

/**
 * getTournamentByOrgAndSlug (auto-injected with browser client)
 */
export async function getTournamentByOrgAndSlug(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentByOrgAndSlug_core(client, ...args);
}

/**
 * checkTournamentSlugAvailable (auto-injected with browser client)
 */
export async function checkTournamentSlugAvailable(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return checkTournamentSlugAvailable_core(client, ...args);
}

/**
 * getTournamentBySlug (auto-injected with browser client)
 */
export async function getTournamentBySlug(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentBySlug_core(client, ...args);
}

/**
 * getTournamentById (auto-injected with browser client)
 */
export async function getTournamentById(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentById_core(client, ...args);
}

/**
 * getTournamentRegistrations (auto-injected with browser client)
 */
export async function getTournamentRegistrations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentRegistrations_core(client, ...args);
}

/**
 * isRegisteredForTournament (auto-injected with browser client)
 */
export async function isRegisteredForTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return isRegisteredForTournament_core(client, ...args);
}

/**
 * getCurrentUserRegisteredTournamentIds (auto-injected with browser client)
 */
export async function getCurrentUserRegisteredTournamentIds(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getCurrentUserRegisteredTournamentIds_core(client, ...args);
}

/**
 * getUserRegistrationDetails (auto-injected with browser client)
 */
export async function getUserRegistrationDetails(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserRegistrationDetails_core(client, ...args);
}

/**
 * getTournamentPhases (auto-injected with browser client)
 */
export async function getTournamentPhases(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentPhases_core(client, ...args);
}

/**
 * getTournamentRounds (auto-injected with browser client)
 */
export async function getTournamentRounds(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentRounds_core(client, ...args);
}

/**
 * getRoundMatches (auto-injected with browser client)
 */
export async function getRoundMatches(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getRoundMatches_core(client, ...args);
}

/**
 * getTournamentStandings (auto-injected with browser client)
 */
export async function getTournamentStandings(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentStandings_core(client, ...args);
}

/**
 * getPlayerTournamentStats (auto-injected with browser client)
 */
export async function getPlayerTournamentStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getPlayerTournamentStats_core(client, ...args);
}

/**
 * getTournamentPlayerStats (auto-injected with browser client)
 */
export async function getTournamentPlayerStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentPlayerStats_core(client, ...args);
}

/**
 * getPhaseRoundsWithStats (auto-injected with browser client)
 */
export async function getPhaseRoundsWithStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getPhaseRoundsWithStats_core(client, ...args);
}

/**
 * getRoundMatchesWithStats (auto-injected with browser client)
 */
export async function getRoundMatchesWithStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getRoundMatchesWithStats_core(client, ...args);
}

/**
 * getPhaseRoundsWithMatches (auto-injected with browser client)
 */
export async function getPhaseRoundsWithMatches(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getPhaseRoundsWithMatches_core(client, ...args);
}

/**
 * getCheckInStatus (auto-injected with browser client)
 */
export async function getCheckInStatus(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getCheckInStatus_core(client, ...args);
}

/**
 * getCheckInStats (auto-injected with browser client)
 */
export async function getCheckInStats(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getCheckInStats_core(client, ...args);
}

/**
 * getUserTeams (auto-injected with browser client)
 */
export async function getUserTeams(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserTeams_core(client, ...args);
}

/**
 * getMatchDetails (auto-injected with browser client)
 */
export async function getMatchDetails(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMatchDetails_core(client, ...args);
}

/**
 * getPlayerMatches (auto-injected with browser client)
 */
export async function getPlayerMatches(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getPlayerMatches_core(client, ...args);
}

/**
 * getTournamentMatchesForStaff (auto-injected with browser client)
 */
export async function getTournamentMatchesForStaff(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentMatchesForStaff_core(client, ...args);
}

/**
 * getMyDashboardData (auto-injected with browser client)
 */
export async function getMyDashboardData(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getMyDashboardData_core(client, ...args);
}

/**
 * getRegistrationStatus (auto-injected with browser client)
 */
export async function getRegistrationStatus(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getRegistrationStatus_core(client, ...args);
}

/**
 * getTournamentInvitationsSent (auto-injected with browser client)
 */
export async function getTournamentInvitationsSent(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentInvitationsSent_core(client, ...args);
}

/**
 * getTournamentInvitationsReceived (auto-injected with browser client)
 */
export async function getTournamentInvitationsReceived(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTournamentInvitationsReceived_core(client, ...args);
}

/**
 * getTeamForRegistration (auto-injected with browser client)
 */
export async function getTeamForRegistration(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getTeamForRegistration_core(client, ...args);
}

/**
 * getUnpairedCheckedInPlayers (auto-injected with browser client)
 */
export async function getUnpairedCheckedInPlayers(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUnpairedCheckedInPlayers_core(client, ...args);
}

/**
 * getUserTournamentHistory (auto-injected with browser client)
 */
export async function getUserTournamentHistory(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserTournamentHistory_core(client, ...args);
}

/**
 * getUserCount (auto-injected with browser client)
 */
export async function getUserCount(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserCount_core(client, ...args);
}

/**
 * getCurrentUser (auto-injected with browser client)
 */
export async function getCurrentUser(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getCurrentUser_core(client, ...args);
}

/**
 * getUserSpritePreference (auto-injected with browser client)
 */
export async function getUserSpritePreference(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserSpritePreference_core(client, ...args);
}

/**
 * getUserById (auto-injected with browser client)
 */
export async function getUserById(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserById_core(client, ...args);
}

/**
 * getUserWithAlt (auto-injected with browser client)
 */
export async function getUserWithAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getUserWithAlt_core(client, ...args);
}

/**
 * getAltByUsername (auto-injected with browser client)
 */
export async function getAltByUsername(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getAltByUsername_core(client, ...args);
}

/**
 * getAltByUserId (auto-injected with browser client)
 */
export async function getAltByUserId(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getAltByUserId_core(client, ...args);
}

/**
 * getAltsByUserId (auto-injected with browser client)
 */
export async function getAltsByUserId(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getAltsByUserId_core(client, ...args);
}

/**
 * getCurrentUserAlts (auto-injected with browser client)
 */
export async function getCurrentUserAlts(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getCurrentUserAlts_core(client, ...args);
}

/**
 * searchAlts (auto-injected with browser client)
 */
export async function searchAlts(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return searchAlts_core(client, ...args);
}

/**
 * getEmailByUsername (auto-injected with browser client)
 */
export async function getEmailByUsername(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return getEmailByUsername_core(client, ...args);
}

/**
 * submitGameSelection (auto-injected with browser client)
 */
export async function submitGameSelection(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return submitGameSelection_core(client, ...args);
}

/**
 * sendMatchMessage (auto-injected with browser client)
 */
export async function sendMatchMessage(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return sendMatchMessage_core(client, ...args);
}

/**
 * sendSystemMessage (auto-injected with browser client)
 */
export async function sendSystemMessage(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return sendSystemMessage_core(client, ...args);
}

/**
 * createMatchGames (auto-injected with browser client)
 */
export async function createMatchGames(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createMatchGames_core(client, ...args);
}

/**
 * judgeOverrideGame (auto-injected with browser client)
 */
export async function judgeOverrideGame(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return judgeOverrideGame_core(client, ...args);
}

/**
 * judgeResetGame (auto-injected with browser client)
 */
export async function judgeResetGame(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return judgeResetGame_core(client, ...args);
}

/**
 * resetMatch (auto-injected with browser client)
 */
export async function resetMatch(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return resetMatch_core(client, ...args);
}

/**
 * markNotificationRead (auto-injected with browser client)
 */
export async function markNotificationRead(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return markNotificationRead_core(client, ...args);
}

/**
 * markAllNotificationsRead (auto-injected with browser client)
 */
export async function markAllNotificationsRead(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return markAllNotificationsRead_core(client, ...args);
}

/**
 * deleteNotification (auto-injected with browser client)
 */
export async function deleteNotification(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return deleteNotification_core(client, ...args);
}

/**
 * createOrganization (auto-injected with browser client)
 */
export async function createOrganization(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createOrganization_core(client, ...args);
}

/**
 * updateOrganization (auto-injected with browser client)
 */
export async function updateOrganization(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateOrganization_core(client, ...args);
}

/**
 * inviteToOrganization (auto-injected with browser client)
 */
export async function inviteToOrganization(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return inviteToOrganization_core(client, ...args);
}

/**
 * acceptOrganizationInvitation (auto-injected with browser client)
 */
export async function acceptOrganizationInvitation(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return acceptOrganizationInvitation_core(client, ...args);
}

/**
 * declineOrganizationInvitation (auto-injected with browser client)
 */
export async function declineOrganizationInvitation(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return declineOrganizationInvitation_core(client, ...args);
}

/**
 * leaveOrganization (auto-injected with browser client)
 */
export async function leaveOrganization(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return leaveOrganization_core(client, ...args);
}

/**
 * removeStaff (auto-injected with browser client)
 */
export async function removeStaff(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return removeStaff_core(client, ...args);
}

/**
 * addStaffMember (auto-injected with browser client)
 */
export async function addStaffMember(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return addStaffMember_core(client, ...args);
}

/**
 * addStaffToGroup (auto-injected with browser client)
 */
export async function addStaffToGroup(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return addStaffToGroup_core(client, ...args);
}

/**
 * removeStaffFromGroup (auto-injected with browser client)
 */
export async function removeStaffFromGroup(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return removeStaffFromGroup_core(client, ...args);
}

/**
 * changeStaffRole (auto-injected with browser client)
 */
export async function changeStaffRole(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return changeStaffRole_core(client, ...args);
}

/**
 * removeStaffCompletely (auto-injected with browser client)
 */
export async function removeStaffCompletely(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return removeStaffCompletely_core(client, ...args);
}

/**
 * updateAlt (auto-injected with browser client)
 */
export async function updateAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateAlt_core(client, ...args);
}

/**
 * updateUsername (auto-injected with browser client)
 */
export async function updateUsername(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateUsername_core(client, ...args);
}

/**
 * ensureAlt (auto-injected with browser client)
 */
export async function ensureAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return ensureAlt_core(client, ...args);
}

/**
 * createAlt (auto-injected with browser client)
 */
export async function createAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createAlt_core(client, ...args);
}

/**
 * deleteAlt (auto-injected with browser client)
 */
export async function deleteAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return deleteAlt_core(client, ...args);
}

/**
 * setMainAlt (auto-injected with browser client)
 */
export async function setMainAlt(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return setMainAlt_core(client, ...args);
}

/**
 * startMatch (auto-injected with browser client)
 */
export async function startMatch(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return startMatch_core(client, ...args);
}

/**
 * reportMatchResult (auto-injected with browser client)
 */
export async function reportMatchResult(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return reportMatchResult_core(client, ...args);
}

/**
 * updatePhase (auto-injected with browser client)
 */
export async function updatePhase(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updatePhase_core(client, ...args);
}

/**
 * createPhase (auto-injected with browser client)
 */
export async function createPhase(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createPhase_core(client, ...args);
}

/**
 * deletePhase (auto-injected with browser client)
 */
export async function deletePhase(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return deletePhase_core(client, ...args);
}

/**
 * saveTournamentPhases (auto-injected with browser client)
 */
export async function saveTournamentPhases(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return saveTournamentPhases_core(client, ...args);
}

/**
 * registerForTournament (auto-injected with browser client)
 */
export async function registerForTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return registerForTournament_core(client, ...args);
}

/**
 * updateRegistrationPreferences (auto-injected with browser client)
 */
export async function updateRegistrationPreferences(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateRegistrationPreferences_core(client, ...args);
}

/**
 * cancelRegistration (auto-injected with browser client)
 */
export async function cancelRegistration(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return cancelRegistration_core(client, ...args);
}

/**
 * updateRegistrationStatus (auto-injected with browser client)
 */
export async function updateRegistrationStatus(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateRegistrationStatus_core(client, ...args);
}

/**
 * checkIn (auto-injected with browser client)
 */
export async function checkIn(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return checkIn_core(client, ...args);
}

/**
 * undoCheckIn (auto-injected with browser client)
 */
export async function undoCheckIn(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return undoCheckIn_core(client, ...args);
}

/**
 * withdrawFromTournament (auto-injected with browser client)
 */
export async function withdrawFromTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return withdrawFromTournament_core(client, ...args);
}

/**
 * sendTournamentInvitations (auto-injected with browser client)
 */
export async function sendTournamentInvitations(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return sendTournamentInvitations_core(client, ...args);
}

/**
 * respondToTournamentInvitation (auto-injected with browser client)
 */
export async function respondToTournamentInvitation(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return respondToTournamentInvitation_core(client, ...args);
}

/**
 * generateRoundPairings (auto-injected with browser client)
 */
export async function generateRoundPairings(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return generateRoundPairings_core(client, ...args);
}

/**
 * startRound (auto-injected with browser client)
 */
export async function startRound(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return startRound_core(client, ...args);
}

/**
 * completeRound (auto-injected with browser client)
 */
export async function completeRound(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return completeRound_core(client, ...args);
}

/**
 * createRound (auto-injected with browser client)
 */
export async function createRound(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createRound_core(client, ...args);
}

/**
 * deleteRoundAndMatches (auto-injected with browser client)
 */
export async function deleteRoundAndMatches(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return deleteRoundAndMatches_core(client, ...args);
}

/**
 * recalculateStandings (auto-injected with browser client)
 */
export async function recalculateStandings(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return recalculateStandings_core(client, ...args);
}

/**
 * dropPlayer (auto-injected with browser client)
 */
export async function dropPlayer(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return dropPlayer_core(client, ...args);
}

/**
 * submitTeam (auto-injected with browser client)
 */
export async function submitTeam(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return submitTeam_core(client, ...args);
}

/**
 * selectTeamForTournament (auto-injected with browser client)
 */
export async function selectTeamForTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return selectTeamForTournament_core(client, ...args);
}

/**
 * createTournament (auto-injected with browser client)
 */
export async function createTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return createTournament_core(client, ...args);
}

/**
 * updateTournament (auto-injected with browser client)
 */
export async function updateTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return updateTournament_core(client, ...args);
}

/**
 * archiveTournament (auto-injected with browser client)
 */
export async function archiveTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return archiveTournament_core(client, ...args);
}

/**
 * deleteTournament (auto-injected with browser client)
 */
export async function deleteTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return deleteTournament_core(client, ...args);
}

/**
 * startTournamentEnhanced (auto-injected with browser client)
 */
export async function startTournamentEnhanced(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return startTournamentEnhanced_core(client, ...args);
}

/**
 * advanceToTopCut (auto-injected with browser client)
 */
export async function advanceToTopCut(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return advanceToTopCut_core(client, ...args);
}

/**
 * generateEliminationPairings (auto-injected with browser client)
 */
export async function generateEliminationPairings(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return generateEliminationPairings_core(client, ...args);
}

/**
 * completeTournament (auto-injected with browser client)
 */
export async function completeTournament(...args: any[]) {
  const client = createBrowserSupabaseClient();
  // @ts-ignore - Variadic argument passing
  return completeTournament_core(client, ...args);
}
