/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: pnpm --filter @trainers/supabase generate-clients
 *
 * Server Client Wrapper (Next.js SSR)
 *
 * All queries and mutations auto-injected with Next.js server Supabase client.
 * This eliminates the need for a service layer - just import from @trainers/supabase/server.
 */

import { createServerSupabaseClient } from "./base/server-client";
import { getPlatformOverview as getPlatformOverview_core } from "../queries/admin-analytics";
import { getUserGrowthStats as getUserGrowthStats_core } from "../queries/admin-analytics";
import { getActiveUserStats as getActiveUserStats_core } from "../queries/admin-analytics";
import { getTournamentStats as getTournamentStats_core } from "../queries/admin-analytics";
import { getOrganizationStats as getOrganizationStats_core } from "../queries/admin-analytics";
import { listCommunitiesAdmin as listCommunitiesAdmin_core } from "../queries/admin-communities";
import { getCommunityAdminDetails as getCommunityAdminDetails_core } from "../queries/admin-communities";
import { approveOrganization as approveOrganization_core } from "../queries/admin-communities";
import { rejectOrganization as rejectOrganization_core } from "../queries/admin-communities";
import { suspendOrganization as suspendOrganization_core } from "../queries/admin-communities";
import { unsuspendOrganization as unsuspendOrganization_core } from "../queries/admin-communities";
import { transferOrgOwnership as transferOrgOwnership_core } from "../queries/admin-communities";
import { listUsersAdmin as listUsersAdmin_core } from "../queries/admin-users";
import { getUserAdminDetails as getUserAdminDetails_core } from "../queries/admin-users";
import { suspendUser as suspendUser_core } from "../queries/admin-users";
import { unsuspendUser as unsuspendUser_core } from "../queries/admin-users";
import { startImpersonation as startImpersonation_core } from "../queries/admin-users";
import { endImpersonation as endImpersonation_core } from "../queries/admin-users";
import { listAnnouncements as listAnnouncements_core } from "../queries/announcements";
import { getActiveAnnouncements as getActiveAnnouncements_core } from "../queries/announcements";
import { createAnnouncement as createAnnouncement_core } from "../queries/announcements";
import { updateAnnouncement as updateAnnouncement_core } from "../queries/announcements";
import { deleteAnnouncement as deleteAnnouncement_core } from "../queries/announcements";
import { getTournamentAuditLog as getTournamentAuditLog_core } from "../queries/audit-log";
import { getMatchAuditLog as getMatchAuditLog_core } from "../queries/audit-log";
import { getAuditLog as getAuditLog_core } from "../queries/audit-log";
import { getAuditLogStats as getAuditLogStats_core } from "../queries/audit-log";
import { listFeatureFlags as listFeatureFlags_core } from "../queries/feature-flags";
import { getFeatureFlag as getFeatureFlag_core } from "../queries/feature-flags";
import { isFeatureEnabled as isFeatureEnabled_core } from "../queries/feature-flags";
import { createFeatureFlag as createFeatureFlag_core } from "../queries/feature-flags";
import { updateFeatureFlag as updateFeatureFlag_core } from "../queries/feature-flags";
import { deleteFeatureFlag as deleteFeatureFlag_core } from "../queries/feature-flags";
import { getMatchGames as getMatchGames_core } from "../queries/match-games";
import { getMatchGamesForPlayer as getMatchGamesForPlayer_core } from "../queries/match-games";
import { getMatchMessages as getMatchMessages_core } from "../queries/match-games";
import { getMatchGame as getMatchGame_core } from "../queries/match-games";
import { getNotificationPreferences as getNotificationPreferences_core } from "../queries/notification-preferences";
import { getNotifications as getNotifications_core } from "../queries/notifications";
import { getNotificationCount as getNotificationCount_core } from "../queries/notifications";
import { getUnreadNotificationCount as getUnreadNotificationCount_core } from "../queries/notifications";
import { getActiveMatchNotifications as getActiveMatchNotifications_core } from "../queries/notifications";
import { getMyOrganizationRequest as getMyOrganizationRequest_core } from "../queries/organization-requests";
import { listOrgRequestsAdmin as listOrgRequestsAdmin_core } from "../queries/organization-requests";
import { listPublicCommunities as listPublicCommunities_core } from "../queries/communities";
import { listCommunities as listCommunities_core } from "../queries/communities";
import { getCommunityBySlug as getCommunityBySlug_core } from "../queries/communities";
import { getCommunityById as getCommunityById_core } from "../queries/communities";
import { listMyCommunities as listMyCommunities_core } from "../queries/communities";
import { canManageCommunity as canManageCommunity_core } from "../queries/communities";
import { listCommunityStaff as listCommunityStaff_core } from "../queries/communities";
import { hasCommunityAccess as hasCommunityAccess_core } from "../queries/communities";
import { getMyCommunityInvitations as getMyCommunityInvitations_core } from "../queries/communities";
import { getCommunityInvitations as getCommunityInvitations_core } from "../queries/communities";
import { listMyOwnedCommunities as listMyOwnedCommunities_core } from "../queries/communities";
import { getCommunityWithTournamentStats as getCommunityWithTournamentStats_core } from "../queries/communities";
import { listCommunityTournaments as listCommunityTournaments_core } from "../queries/communities";
import { listCommunityStaffWithRoles as listCommunityStaffWithRoles_core } from "../queries/communities";
import { listCommunityGroups as listCommunityGroups_core } from "../queries/communities";
import { searchUsersForInvite as searchUsersForInvite_core } from "../queries/communities";
import { hasOrgPermission as hasOrgPermission_core } from "../queries/communities";
import { getUserPermissions as getUserPermissions_core } from "../queries/permissions";
import { hasPermission as hasPermission_core } from "../queries/permissions";
import { searchPlayers as searchPlayers_core } from "../queries/players";
import { getLeaderboard as getLeaderboard_core } from "../queries/players";
import { getRecentlyActivePlayers as getRecentlyActivePlayers_core } from "../queries/players";
import { getNewMembers as getNewMembers_core } from "../queries/players";
import { getPlayerRating as getPlayerRating_core } from "../queries/ratings";
import { isSiteAdmin as isSiteAdmin_core } from "../queries/site-roles";
import { getSiteRoles as getSiteRoles_core } from "../queries/site-roles";
import { getSiteAdmins as getSiteAdmins_core } from "../queries/site-roles";
import { getUserSiteRoles as getUserSiteRoles_core } from "../queries/site-roles";
import { grantSiteRole as grantSiteRole_core } from "../queries/site-roles";
import { revokeSiteRole as revokeSiteRole_core } from "../queries/site-roles";
import { getActiveSudoSession as getActiveSudoSession_core } from "../queries/sudo-mode";
import { isSudoModeActive as isSudoModeActive_core } from "../queries/sudo-mode";
import { getSudoSessions as getSudoSessions_core } from "../queries/sudo-mode";
import { startSudoSession as startSudoSession_core } from "../queries/sudo-mode";
import { endSudoSession as endSudoSession_core } from "../queries/sudo-mode";
import { listTournamentsGrouped as listTournamentsGrouped_core } from "../queries/tournaments";
import { listPublicTournaments as listPublicTournaments_core } from "../queries/tournaments";
import { listTournaments as listTournaments_core } from "../queries/tournaments";
import { getTournamentByOrgAndSlug as getTournamentByOrgAndSlug_core } from "../queries/tournaments";
import { checkTournamentSlugAvailable as checkTournamentSlugAvailable_core } from "../queries/tournaments";
import { getTournamentBySlug as getTournamentBySlug_core } from "../queries/tournaments";
import { getTournamentById as getTournamentById_core } from "../queries/tournaments";
import { getTournamentRegistrations as getTournamentRegistrations_core } from "../queries/tournaments";
import { isRegisteredForTournament as isRegisteredForTournament_core } from "../queries/tournaments";
import { getCurrentUserRegisteredTournamentIds as getCurrentUserRegisteredTournamentIds_core } from "../queries/tournaments";
import { getUserRegistrationDetails as getUserRegistrationDetails_core } from "../queries/tournaments";
import { getTournamentPhases as getTournamentPhases_core } from "../queries/tournaments";
import { getTournamentRounds as getTournamentRounds_core } from "../queries/tournaments";
import { getRoundMatches as getRoundMatches_core } from "../queries/tournaments";
import { getTournamentStandings as getTournamentStandings_core } from "../queries/tournaments";
import { getPlayerTournamentStats as getPlayerTournamentStats_core } from "../queries/tournaments";
import { getTournamentPlayerStats as getTournamentPlayerStats_core } from "../queries/tournaments";
import { getPhaseRoundsWithStats as getPhaseRoundsWithStats_core } from "../queries/tournaments";
import { getRoundMatchesWithStats as getRoundMatchesWithStats_core } from "../queries/tournaments";
import { getPhaseRoundsWithMatches as getPhaseRoundsWithMatches_core } from "../queries/tournaments";
import { getCheckInStatus as getCheckInStatus_core } from "../queries/tournaments";
import { getCheckInStats as getCheckInStats_core } from "../queries/tournaments";
import { getUserTeams as getUserTeams_core } from "../queries/tournaments";
import { getMatchDetails as getMatchDetails_core } from "../queries/tournaments";
import { getMatchByRoundAndTable as getMatchByRoundAndTable_core } from "../queries/tournaments";
import { getPlayerMatches as getPlayerMatches_core } from "../queries/tournaments";
import { getTournamentMatchesForStaff as getTournamentMatchesForStaff_core } from "../queries/tournaments";
import { getActiveMatch as getActiveMatch_core } from "../queries/tournaments";
import { getMyDashboardData as getMyDashboardData_core } from "../queries/tournaments";
import { getRegistrationStatus as getRegistrationStatus_core } from "../queries/tournaments";
import { getTournamentInvitationsSent as getTournamentInvitationsSent_core } from "../queries/tournaments";
import { getTournamentInvitationsReceived as getTournamentInvitationsReceived_core } from "../queries/tournaments";
import { getTeamForRegistration as getTeamForRegistration_core } from "../queries/tournaments";
import { getUnpairedCheckedInPlayers as getUnpairedCheckedInPlayers_core } from "../queries/tournaments";
import { getUserTournamentHistory as getUserTournamentHistory_core } from "../queries/tournaments";
import { getPlayerTournamentHistory as getPlayerTournamentHistory_core } from "../queries/tournaments";
import { getPlayerLifetimeStats as getPlayerLifetimeStats_core } from "../queries/tournaments";
import { getUserCount as getUserCount_core } from "../queries/users";
import { getCurrentUser as getCurrentUser_core } from "../queries/users";
import { getUserSpritePreference as getUserSpritePreference_core } from "../queries/users";
import { getUserById as getUserById_core } from "../queries/users";
import { getUserWithAlt as getUserWithAlt_core } from "../queries/users";
import { getAltByUsername as getAltByUsername_core } from "../queries/users";
import { getAltByUserId as getAltByUserId_core } from "../queries/users";
import { getAltsByUserId as getAltsByUserId_core } from "../queries/users";
import { getCurrentUserAlts as getCurrentUserAlts_core } from "../queries/users";
import { searchAlts as searchAlts_core } from "../queries/users";
import { getPlayerProfileByHandle as getPlayerProfileByHandle_core } from "../queries/users";
import { getEmailByUsername as getEmailByUsername_core } from "../queries/users";
import { getFollowerCount as getFollowerCount_core } from "../queries/users";
import { getFollowingCount as getFollowingCount_core } from "../queries/users";
import { getPlayerTournamentHistoryFull as getPlayerTournamentHistoryFull_core } from "../queries/users";
import { getPlayerPublicTeams as getPlayerPublicTeams_core } from "../queries/users";
import { submitGameSelection as submitGameSelection_core } from "../mutations/match-games";
import { sendMatchMessage as sendMatchMessage_core } from "../mutations/match-games";
import { sendSystemMessage as sendSystemMessage_core } from "../mutations/match-games";
import { createMatchGames as createMatchGames_core } from "../mutations/match-games";
import { judgeOverrideGame as judgeOverrideGame_core } from "../mutations/match-games";
import { judgeResetGame as judgeResetGame_core } from "../mutations/match-games";
import { resetMatch as resetMatch_core } from "../mutations/match-games";
import { confirmMatchCheckIn as confirmMatchCheckIn_core } from "../mutations/match-games";
import { upsertNotificationPreferences as upsertNotificationPreferences_core } from "../mutations/notification-preferences";
import { markNotificationRead as markNotificationRead_core } from "../mutations/notifications";
import { markAllNotificationsRead as markAllNotificationsRead_core } from "../mutations/notifications";
import { deleteNotification as deleteNotification_core } from "../mutations/notifications";
import { submitCommunityRequest as submitCommunityRequest_core } from "../mutations/organization-requests";
import { approveCommunityRequest as approveCommunityRequest_core } from "../mutations/organization-requests";
import { rejectCommunityRequest as rejectCommunityRequest_core } from "../mutations/organization-requests";
import { createCommunity as createCommunity_core } from "../mutations/communities";
import { updateCommunity as updateCommunity_core } from "../mutations/communities";
import { inviteToCommunity as inviteToCommunity_core } from "../mutations/communities";
import { acceptCommunityInvitation as acceptCommunityInvitation_core } from "../mutations/communities";
import { declineCommunityInvitation as declineCommunityInvitation_core } from "../mutations/communities";
import { leaveCommunity as leaveCommunity_core } from "../mutations/communities";
import { removeStaff as removeStaff_core } from "../mutations/communities";
import { addStaffMember as addStaffMember_core } from "../mutations/communities";
import { addStaffToGroup as addStaffToGroup_core } from "../mutations/communities";
import { removeStaffFromGroup as removeStaffFromGroup_core } from "../mutations/communities";
import { changeStaffRole as changeStaffRole_core } from "../mutations/communities";
import { removeStaffCompletely as removeStaffCompletely_core } from "../mutations/communities";
import { updateAlt as updateAlt_core } from "../mutations/users";
import { updateUsername as updateUsername_core } from "../mutations/users";
import { ensureAlt as ensureAlt_core } from "../mutations/users";
import { createAlt as createAlt_core } from "../mutations/users";
import { deleteAlt as deleteAlt_core } from "../mutations/users";
import { setMainAlt as setMainAlt_core } from "../mutations/users";
import { startMatch as startMatch_core } from "../mutations/tournaments/matches";
import { reportMatchResult as reportMatchResult_core } from "../mutations/tournaments/matches";
import { updatePhase as updatePhase_core } from "../mutations/tournaments/phases";
import { createPhase as createPhase_core } from "../mutations/tournaments/phases";
import { deletePhase as deletePhase_core } from "../mutations/tournaments/phases";
import { saveTournamentPhases as saveTournamentPhases_core } from "../mutations/tournaments/phases";
import { registerForTournament as registerForTournament_core } from "../mutations/tournaments/registration";
import { updateRegistrationPreferences as updateRegistrationPreferences_core } from "../mutations/tournaments/registration";
import { cancelRegistration as cancelRegistration_core } from "../mutations/tournaments/registration";
import { updateRegistrationStatus as updateRegistrationStatus_core } from "../mutations/tournaments/registration";
import { checkIn as checkIn_core } from "../mutations/tournaments/registration";
import { undoCheckIn as undoCheckIn_core } from "../mutations/tournaments/registration";
import { withdrawFromTournament as withdrawFromTournament_core } from "../mutations/tournaments/registration";
import { sendTournamentInvitations as sendTournamentInvitations_core } from "../mutations/tournaments/registration";
import { respondToTournamentInvitation as respondToTournamentInvitation_core } from "../mutations/tournaments/registration";
import { generateRoundPairings as generateRoundPairings_core } from "../mutations/tournaments/rounds";
import { startRound as startRound_core } from "../mutations/tournaments/rounds";
import { completeRound as completeRound_core } from "../mutations/tournaments/rounds";
import { createRound as createRound_core } from "../mutations/tournaments/rounds";
import { deleteRoundAndMatches as deleteRoundAndMatches_core } from "../mutations/tournaments/rounds";
import { recalculateStandings as recalculateStandings_core } from "../mutations/tournaments/standings";
import { dropPlayer as dropPlayer_core } from "../mutations/tournaments/standings";
import { submitTeam as submitTeam_core } from "../mutations/tournaments/teams";
import { selectTeamForTournament as selectTeamForTournament_core } from "../mutations/tournaments/teams";
import { createTournament as createTournament_core } from "../mutations/tournaments/tournament-crud";
import { updateTournament as updateTournament_core } from "../mutations/tournaments/tournament-crud";
import { archiveTournament as archiveTournament_core } from "../mutations/tournaments/tournament-crud";
import { deleteTournament as deleteTournament_core } from "../mutations/tournaments/tournament-crud";
import { startTournamentEnhanced as startTournamentEnhanced_core } from "../mutations/tournaments/tournament-flow";
import { advanceToTopCut as advanceToTopCut_core } from "../mutations/tournaments/tournament-flow";
import { generateEliminationPairings as generateEliminationPairings_core } from "../mutations/tournaments/tournament-flow";
import { completeTournament as completeTournament_core } from "../mutations/tournaments/tournament-flow";

/**
 * getPlatformOverview (auto-injected with server client)
 */
export async function getPlatformOverview(
  ...args: Parameters<typeof getPlatformOverview_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlatformOverview_core>>> {
  const client = await createServerSupabaseClient();
  return getPlatformOverview_core(client, ...args);
}

/**
 * getUserGrowthStats (auto-injected with server client)
 */
export async function getUserGrowthStats(
  ...args: Parameters<typeof getUserGrowthStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserGrowthStats_core>>> {
  const client = await createServerSupabaseClient();
  return getUserGrowthStats_core(client, ...args);
}

/**
 * getActiveUserStats (auto-injected with server client)
 */
export async function getActiveUserStats(
  ...args: Parameters<typeof getActiveUserStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getActiveUserStats_core>>> {
  const client = await createServerSupabaseClient();
  return getActiveUserStats_core(client, ...args);
}

/**
 * getTournamentStats (auto-injected with server client)
 */
export async function getTournamentStats(
  ...args: Parameters<typeof getTournamentStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentStats_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentStats_core(client, ...args);
}

/**
 * getOrganizationStats (auto-injected with server client)
 */
export async function getOrganizationStats(
  ...args: Parameters<typeof getOrganizationStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getOrganizationStats_core>>> {
  const client = await createServerSupabaseClient();
  return getOrganizationStats_core(client, ...args);
}

/**
 * listCommunitiesAdmin (auto-injected with server client)
 */
export async function listCommunitiesAdmin(
  ...args: Parameters<typeof listCommunitiesAdmin_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunitiesAdmin_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunitiesAdmin_core(client, ...args);
}

/**
 * getCommunityAdminDetails (auto-injected with server client)
 */
export async function getCommunityAdminDetails(
  ...args: Parameters<typeof getCommunityAdminDetails_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCommunityAdminDetails_core>>> {
  const client = await createServerSupabaseClient();
  return getCommunityAdminDetails_core(client, ...args);
}

/**
 * approveOrganization (auto-injected with server client)
 */
export async function approveOrganization(
  ...args: Parameters<typeof approveOrganization_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof approveOrganization_core>>> {
  const client = await createServerSupabaseClient();
  return approveOrganization_core(client, ...args);
}

/**
 * rejectOrganization (auto-injected with server client)
 */
export async function rejectOrganization(
  ...args: Parameters<typeof rejectOrganization_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof rejectOrganization_core>>> {
  const client = await createServerSupabaseClient();
  return rejectOrganization_core(client, ...args);
}

/**
 * suspendOrganization (auto-injected with server client)
 */
export async function suspendOrganization(
  ...args: Parameters<typeof suspendOrganization_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof suspendOrganization_core>>> {
  const client = await createServerSupabaseClient();
  return suspendOrganization_core(client, ...args);
}

/**
 * unsuspendOrganization (auto-injected with server client)
 */
export async function unsuspendOrganization(
  ...args: Parameters<typeof unsuspendOrganization_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof unsuspendOrganization_core>>> {
  const client = await createServerSupabaseClient();
  return unsuspendOrganization_core(client, ...args);
}

/**
 * transferOrgOwnership (auto-injected with server client)
 */
export async function transferOrgOwnership(
  ...args: Parameters<typeof transferOrgOwnership_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof transferOrgOwnership_core>>> {
  const client = await createServerSupabaseClient();
  return transferOrgOwnership_core(client, ...args);
}

/**
 * listUsersAdmin (auto-injected with server client)
 */
export async function listUsersAdmin(
  ...args: Parameters<typeof listUsersAdmin_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listUsersAdmin_core>>> {
  const client = await createServerSupabaseClient();
  return listUsersAdmin_core(client, ...args);
}

/**
 * getUserAdminDetails (auto-injected with server client)
 */
export async function getUserAdminDetails(
  ...args: Parameters<typeof getUserAdminDetails_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserAdminDetails_core>>> {
  const client = await createServerSupabaseClient();
  return getUserAdminDetails_core(client, ...args);
}

/**
 * suspendUser (auto-injected with server client)
 */
export async function suspendUser(
  ...args: Parameters<typeof suspendUser_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof suspendUser_core>>> {
  const client = await createServerSupabaseClient();
  return suspendUser_core(client, ...args);
}

/**
 * unsuspendUser (auto-injected with server client)
 */
export async function unsuspendUser(
  ...args: Parameters<typeof unsuspendUser_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof unsuspendUser_core>>> {
  const client = await createServerSupabaseClient();
  return unsuspendUser_core(client, ...args);
}

/**
 * startImpersonation (auto-injected with server client)
 */
export async function startImpersonation(
  ...args: Parameters<typeof startImpersonation_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof startImpersonation_core>>> {
  const client = await createServerSupabaseClient();
  return startImpersonation_core(client, ...args);
}

/**
 * endImpersonation (auto-injected with server client)
 */
export async function endImpersonation(
  ...args: Parameters<typeof endImpersonation_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof endImpersonation_core>>> {
  const client = await createServerSupabaseClient();
  return endImpersonation_core(client, ...args);
}

/**
 * listAnnouncements (auto-injected with server client)
 */
export async function listAnnouncements(
  ...args: Parameters<typeof listAnnouncements_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listAnnouncements_core>>> {
  const client = await createServerSupabaseClient();
  return listAnnouncements_core(client, ...args);
}

/**
 * getActiveAnnouncements (auto-injected with server client)
 */
export async function getActiveAnnouncements(
  ...args: Parameters<typeof getActiveAnnouncements_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getActiveAnnouncements_core>>> {
  const client = await createServerSupabaseClient();
  return getActiveAnnouncements_core(client, ...args);
}

/**
 * createAnnouncement (auto-injected with server client)
 */
export async function createAnnouncement(
  ...args: Parameters<typeof createAnnouncement_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createAnnouncement_core>>> {
  const client = await createServerSupabaseClient();
  return createAnnouncement_core(client, ...args);
}

/**
 * updateAnnouncement (auto-injected with server client)
 */
export async function updateAnnouncement(
  ...args: Parameters<typeof updateAnnouncement_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateAnnouncement_core>>> {
  const client = await createServerSupabaseClient();
  return updateAnnouncement_core(client, ...args);
}

/**
 * deleteAnnouncement (auto-injected with server client)
 */
export async function deleteAnnouncement(
  ...args: Parameters<typeof deleteAnnouncement_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteAnnouncement_core>>> {
  const client = await createServerSupabaseClient();
  return deleteAnnouncement_core(client, ...args);
}

/**
 * getTournamentAuditLog (auto-injected with server client)
 */
export async function getTournamentAuditLog(
  ...args: Parameters<typeof getTournamentAuditLog_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentAuditLog_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentAuditLog_core(client, ...args);
}

/**
 * getMatchAuditLog (auto-injected with server client)
 */
export async function getMatchAuditLog(
  ...args: Parameters<typeof getMatchAuditLog_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchAuditLog_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchAuditLog_core(client, ...args);
}

/**
 * getAuditLog (auto-injected with server client)
 */
export async function getAuditLog(
  ...args: Parameters<typeof getAuditLog_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getAuditLog_core>>> {
  const client = await createServerSupabaseClient();
  return getAuditLog_core(client, ...args);
}

/**
 * getAuditLogStats (auto-injected with server client)
 */
export async function getAuditLogStats(
  ...args: Parameters<typeof getAuditLogStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getAuditLogStats_core>>> {
  const client = await createServerSupabaseClient();
  return getAuditLogStats_core(client, ...args);
}

/**
 * listFeatureFlags (auto-injected with server client)
 */
export async function listFeatureFlags(
  ...args: Parameters<typeof listFeatureFlags_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listFeatureFlags_core>>> {
  const client = await createServerSupabaseClient();
  return listFeatureFlags_core(client, ...args);
}

/**
 * getFeatureFlag (auto-injected with server client)
 */
export async function getFeatureFlag(
  ...args: Parameters<typeof getFeatureFlag_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getFeatureFlag_core>>> {
  const client = await createServerSupabaseClient();
  return getFeatureFlag_core(client, ...args);
}

/**
 * isFeatureEnabled (auto-injected with server client)
 */
export async function isFeatureEnabled(
  ...args: Parameters<typeof isFeatureEnabled_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof isFeatureEnabled_core>>> {
  const client = await createServerSupabaseClient();
  return isFeatureEnabled_core(client, ...args);
}

/**
 * createFeatureFlag (auto-injected with server client)
 */
export async function createFeatureFlag(
  ...args: Parameters<typeof createFeatureFlag_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createFeatureFlag_core>>> {
  const client = await createServerSupabaseClient();
  return createFeatureFlag_core(client, ...args);
}

/**
 * updateFeatureFlag (auto-injected with server client)
 */
export async function updateFeatureFlag(
  ...args: Parameters<typeof updateFeatureFlag_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateFeatureFlag_core>>> {
  const client = await createServerSupabaseClient();
  return updateFeatureFlag_core(client, ...args);
}

/**
 * deleteFeatureFlag (auto-injected with server client)
 */
export async function deleteFeatureFlag(
  ...args: Parameters<typeof deleteFeatureFlag_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteFeatureFlag_core>>> {
  const client = await createServerSupabaseClient();
  return deleteFeatureFlag_core(client, ...args);
}

/**
 * getMatchGames (auto-injected with server client)
 */
export async function getMatchGames(
  ...args: Parameters<typeof getMatchGames_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchGames_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchGames_core(client, ...args);
}

/**
 * getMatchGamesForPlayer (auto-injected with server client)
 */
export async function getMatchGamesForPlayer(
  ...args: Parameters<typeof getMatchGamesForPlayer_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchGamesForPlayer_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchGamesForPlayer_core(client, ...args);
}

/**
 * getMatchMessages (auto-injected with server client)
 */
export async function getMatchMessages(
  ...args: Parameters<typeof getMatchMessages_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchMessages_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchMessages_core(client, ...args);
}

/**
 * getMatchGame (auto-injected with server client)
 */
export async function getMatchGame(
  ...args: Parameters<typeof getMatchGame_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchGame_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchGame_core(client, ...args);
}

/**
 * getNotificationPreferences (auto-injected with server client)
 */
export async function getNotificationPreferences(
  ...args: Parameters<typeof getNotificationPreferences_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getNotificationPreferences_core>>> {
  const client = await createServerSupabaseClient();
  return getNotificationPreferences_core(client, ...args);
}

/**
 * getNotifications (auto-injected with server client)
 */
export async function getNotifications(
  ...args: Parameters<typeof getNotifications_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getNotifications_core>>> {
  const client = await createServerSupabaseClient();
  return getNotifications_core(client, ...args);
}

/**
 * getNotificationCount (auto-injected with server client)
 */
export async function getNotificationCount(
  ...args: Parameters<typeof getNotificationCount_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getNotificationCount_core>>> {
  const client = await createServerSupabaseClient();
  return getNotificationCount_core(client, ...args);
}

/**
 * getUnreadNotificationCount (auto-injected with server client)
 */
export async function getUnreadNotificationCount(
  ...args: Parameters<typeof getUnreadNotificationCount_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUnreadNotificationCount_core>>> {
  const client = await createServerSupabaseClient();
  return getUnreadNotificationCount_core(client, ...args);
}

/**
 * getActiveMatchNotifications (auto-injected with server client)
 */
export async function getActiveMatchNotifications(
  ...args: Parameters<typeof getActiveMatchNotifications_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getActiveMatchNotifications_core>>> {
  const client = await createServerSupabaseClient();
  return getActiveMatchNotifications_core(client, ...args);
}

/**
 * getMyOrganizationRequest (auto-injected with server client)
 */
export async function getMyOrganizationRequest(
  ...args: Parameters<typeof getMyOrganizationRequest_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMyOrganizationRequest_core>>> {
  const client = await createServerSupabaseClient();
  return getMyOrganizationRequest_core(client, ...args);
}

/**
 * listOrgRequestsAdmin (auto-injected with server client)
 */
export async function listOrgRequestsAdmin(
  ...args: Parameters<typeof listOrgRequestsAdmin_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listOrgRequestsAdmin_core>>> {
  const client = await createServerSupabaseClient();
  return listOrgRequestsAdmin_core(client, ...args);
}

/**
 * listPublicCommunities (auto-injected with server client)
 */
export async function listPublicCommunities(
  ...args: Parameters<typeof listPublicCommunities_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listPublicCommunities_core>>> {
  const client = await createServerSupabaseClient();
  return listPublicCommunities_core(client, ...args);
}

/**
 * listCommunities (auto-injected with server client)
 */
export async function listCommunities(
  ...args: Parameters<typeof listCommunities_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunities_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunities_core(client, ...args);
}

/**
 * getCommunityBySlug (auto-injected with server client)
 */
export async function getCommunityBySlug(
  ...args: Parameters<typeof getCommunityBySlug_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCommunityBySlug_core>>> {
  const client = await createServerSupabaseClient();
  return getCommunityBySlug_core(client, ...args);
}

/**
 * getCommunityById (auto-injected with server client)
 */
export async function getCommunityById(
  ...args: Parameters<typeof getCommunityById_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCommunityById_core>>> {
  const client = await createServerSupabaseClient();
  return getCommunityById_core(client, ...args);
}

/**
 * listMyCommunities (auto-injected with server client)
 */
export async function listMyCommunities(
  ...args: Parameters<typeof listMyCommunities_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listMyCommunities_core>>> {
  const client = await createServerSupabaseClient();
  return listMyCommunities_core(client, ...args);
}

/**
 * canManageCommunity (auto-injected with server client)
 */
export async function canManageCommunity(
  ...args: Parameters<typeof canManageCommunity_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof canManageCommunity_core>>> {
  const client = await createServerSupabaseClient();
  return canManageCommunity_core(client, ...args);
}

/**
 * listCommunityStaff (auto-injected with server client)
 */
export async function listCommunityStaff(
  ...args: Parameters<typeof listCommunityStaff_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunityStaff_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunityStaff_core(client, ...args);
}

/**
 * hasCommunityAccess (auto-injected with server client)
 */
export async function hasCommunityAccess(
  ...args: Parameters<typeof hasCommunityAccess_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof hasCommunityAccess_core>>> {
  const client = await createServerSupabaseClient();
  return hasCommunityAccess_core(client, ...args);
}

/**
 * getMyCommunityInvitations (auto-injected with server client)
 */
export async function getMyCommunityInvitations(
  ...args: Parameters<typeof getMyCommunityInvitations_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMyCommunityInvitations_core>>> {
  const client = await createServerSupabaseClient();
  return getMyCommunityInvitations_core(client, ...args);
}

/**
 * getCommunityInvitations (auto-injected with server client)
 */
export async function getCommunityInvitations(
  ...args: Parameters<typeof getCommunityInvitations_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCommunityInvitations_core>>> {
  const client = await createServerSupabaseClient();
  return getCommunityInvitations_core(client, ...args);
}

/**
 * listMyOwnedCommunities (auto-injected with server client)
 */
export async function listMyOwnedCommunities(
  ...args: Parameters<typeof listMyOwnedCommunities_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listMyOwnedCommunities_core>>> {
  const client = await createServerSupabaseClient();
  return listMyOwnedCommunities_core(client, ...args);
}

/**
 * getCommunityWithTournamentStats (auto-injected with server client)
 */
export async function getCommunityWithTournamentStats(
  ...args: Parameters<typeof getCommunityWithTournamentStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCommunityWithTournamentStats_core>>> {
  const client = await createServerSupabaseClient();
  return getCommunityWithTournamentStats_core(client, ...args);
}

/**
 * listCommunityTournaments (auto-injected with server client)
 */
export async function listCommunityTournaments(
  ...args: Parameters<typeof listCommunityTournaments_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunityTournaments_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunityTournaments_core(client, ...args);
}

/**
 * listCommunityStaffWithRoles (auto-injected with server client)
 */
export async function listCommunityStaffWithRoles(
  ...args: Parameters<typeof listCommunityStaffWithRoles_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunityStaffWithRoles_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunityStaffWithRoles_core(client, ...args);
}

/**
 * listCommunityGroups (auto-injected with server client)
 */
export async function listCommunityGroups(
  ...args: Parameters<typeof listCommunityGroups_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listCommunityGroups_core>>> {
  const client = await createServerSupabaseClient();
  return listCommunityGroups_core(client, ...args);
}

/**
 * searchUsersForInvite (auto-injected with server client)
 */
export async function searchUsersForInvite(
  ...args: Parameters<typeof searchUsersForInvite_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof searchUsersForInvite_core>>> {
  const client = await createServerSupabaseClient();
  return searchUsersForInvite_core(client, ...args);
}

/**
 * hasOrgPermission (auto-injected with server client)
 */
export async function hasOrgPermission(
  ...args: Parameters<typeof hasOrgPermission_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof hasOrgPermission_core>>> {
  const client = await createServerSupabaseClient();
  return hasOrgPermission_core(client, ...args);
}

/**
 * getUserPermissions (auto-injected with server client)
 */
export async function getUserPermissions(
  ...args: Parameters<typeof getUserPermissions_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserPermissions_core>>> {
  const client = await createServerSupabaseClient();
  return getUserPermissions_core(client, ...args);
}

/**
 * hasPermission (auto-injected with server client)
 */
export async function hasPermission(
  ...args: Parameters<typeof hasPermission_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof hasPermission_core>>> {
  const client = await createServerSupabaseClient();
  return hasPermission_core(client, ...args);
}

/**
 * searchPlayers (auto-injected with server client)
 */
export async function searchPlayers(
  ...args: Parameters<typeof searchPlayers_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof searchPlayers_core>>> {
  const client = await createServerSupabaseClient();
  return searchPlayers_core(client, ...args);
}

/**
 * getLeaderboard (auto-injected with server client)
 */
export async function getLeaderboard(
  ...args: Parameters<typeof getLeaderboard_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getLeaderboard_core>>> {
  const client = await createServerSupabaseClient();
  return getLeaderboard_core(client, ...args);
}

/**
 * getRecentlyActivePlayers (auto-injected with server client)
 */
export async function getRecentlyActivePlayers(
  ...args: Parameters<typeof getRecentlyActivePlayers_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getRecentlyActivePlayers_core>>> {
  const client = await createServerSupabaseClient();
  return getRecentlyActivePlayers_core(client, ...args);
}

/**
 * getNewMembers (auto-injected with server client)
 */
export async function getNewMembers(
  ...args: Parameters<typeof getNewMembers_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getNewMembers_core>>> {
  const client = await createServerSupabaseClient();
  return getNewMembers_core(client, ...args);
}

/**
 * getPlayerRating (auto-injected with server client)
 */
export async function getPlayerRating(
  ...args: Parameters<typeof getPlayerRating_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerRating_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerRating_core(client, ...args);
}

/**
 * isSiteAdmin (auto-injected with server client)
 */
export async function isSiteAdmin(
  ...args: Parameters<typeof isSiteAdmin_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof isSiteAdmin_core>>> {
  const client = await createServerSupabaseClient();
  return isSiteAdmin_core(client, ...args);
}

/**
 * getSiteRoles (auto-injected with server client)
 */
export async function getSiteRoles(
  ...args: Parameters<typeof getSiteRoles_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getSiteRoles_core>>> {
  const client = await createServerSupabaseClient();
  return getSiteRoles_core(client, ...args);
}

/**
 * getSiteAdmins (auto-injected with server client)
 */
export async function getSiteAdmins(
  ...args: Parameters<typeof getSiteAdmins_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getSiteAdmins_core>>> {
  const client = await createServerSupabaseClient();
  return getSiteAdmins_core(client, ...args);
}

/**
 * getUserSiteRoles (auto-injected with server client)
 */
export async function getUserSiteRoles(
  ...args: Parameters<typeof getUserSiteRoles_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserSiteRoles_core>>> {
  const client = await createServerSupabaseClient();
  return getUserSiteRoles_core(client, ...args);
}

/**
 * grantSiteRole (auto-injected with server client)
 */
export async function grantSiteRole(
  ...args: Parameters<typeof grantSiteRole_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof grantSiteRole_core>>> {
  const client = await createServerSupabaseClient();
  return grantSiteRole_core(client, ...args);
}

/**
 * revokeSiteRole (auto-injected with server client)
 */
export async function revokeSiteRole(
  ...args: Parameters<typeof revokeSiteRole_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof revokeSiteRole_core>>> {
  const client = await createServerSupabaseClient();
  return revokeSiteRole_core(client, ...args);
}

/**
 * getActiveSudoSession (auto-injected with server client)
 */
export async function getActiveSudoSession(
  ...args: Parameters<typeof getActiveSudoSession_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getActiveSudoSession_core>>> {
  const client = await createServerSupabaseClient();
  return getActiveSudoSession_core(client, ...args);
}

/**
 * isSudoModeActive (auto-injected with server client)
 */
export async function isSudoModeActive(
  ...args: Parameters<typeof isSudoModeActive_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof isSudoModeActive_core>>> {
  const client = await createServerSupabaseClient();
  return isSudoModeActive_core(client, ...args);
}

/**
 * getSudoSessions (auto-injected with server client)
 */
export async function getSudoSessions(
  ...args: Parameters<typeof getSudoSessions_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getSudoSessions_core>>> {
  const client = await createServerSupabaseClient();
  return getSudoSessions_core(client, ...args);
}

/**
 * startSudoSession (auto-injected with server client)
 */
export async function startSudoSession(
  ...args: Parameters<typeof startSudoSession_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof startSudoSession_core>>> {
  const client = await createServerSupabaseClient();
  return startSudoSession_core(client, ...args);
}

/**
 * endSudoSession (auto-injected with server client)
 */
export async function endSudoSession(
  ...args: Parameters<typeof endSudoSession_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof endSudoSession_core>>> {
  const client = await createServerSupabaseClient();
  return endSudoSession_core(client, ...args);
}

/**
 * listTournamentsGrouped (auto-injected with server client)
 */
export async function listTournamentsGrouped(
  ...args: Parameters<typeof listTournamentsGrouped_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listTournamentsGrouped_core>>> {
  const client = await createServerSupabaseClient();
  return listTournamentsGrouped_core(client, ...args);
}

/**
 * listPublicTournaments (auto-injected with server client)
 */
export async function listPublicTournaments(
  ...args: Parameters<typeof listPublicTournaments_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listPublicTournaments_core>>> {
  const client = await createServerSupabaseClient();
  return listPublicTournaments_core(client, ...args);
}

/**
 * listTournaments (auto-injected with server client)
 */
export async function listTournaments(
  ...args: Parameters<typeof listTournaments_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof listTournaments_core>>> {
  const client = await createServerSupabaseClient();
  return listTournaments_core(client, ...args);
}

/**
 * getTournamentByOrgAndSlug (auto-injected with server client)
 */
export async function getTournamentByOrgAndSlug(
  ...args: Parameters<typeof getTournamentByOrgAndSlug_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentByOrgAndSlug_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentByOrgAndSlug_core(client, ...args);
}

/**
 * checkTournamentSlugAvailable (auto-injected with server client)
 */
export async function checkTournamentSlugAvailable(
  ...args: Parameters<typeof checkTournamentSlugAvailable_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof checkTournamentSlugAvailable_core>>> {
  const client = await createServerSupabaseClient();
  return checkTournamentSlugAvailable_core(client, ...args);
}

/**
 * getTournamentBySlug (auto-injected with server client)
 */
export async function getTournamentBySlug(
  ...args: Parameters<typeof getTournamentBySlug_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentBySlug_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentBySlug_core(client, ...args);
}

/**
 * getTournamentById (auto-injected with server client)
 */
export async function getTournamentById(
  ...args: Parameters<typeof getTournamentById_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentById_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentById_core(client, ...args);
}

/**
 * getTournamentRegistrations (auto-injected with server client)
 */
export async function getTournamentRegistrations(
  ...args: Parameters<typeof getTournamentRegistrations_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentRegistrations_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentRegistrations_core(client, ...args);
}

/**
 * isRegisteredForTournament (auto-injected with server client)
 */
export async function isRegisteredForTournament(
  ...args: Parameters<typeof isRegisteredForTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof isRegisteredForTournament_core>>> {
  const client = await createServerSupabaseClient();
  return isRegisteredForTournament_core(client, ...args);
}

/**
 * getCurrentUserRegisteredTournamentIds (auto-injected with server client)
 */
export async function getCurrentUserRegisteredTournamentIds(
  ...args: Parameters<
    typeof getCurrentUserRegisteredTournamentIds_core
  > extends [first: infer _F, ...rest: infer R]
    ? R
    : never
): Promise<
  Awaited<ReturnType<typeof getCurrentUserRegisteredTournamentIds_core>>
> {
  const client = await createServerSupabaseClient();
  return getCurrentUserRegisteredTournamentIds_core(client, ...args);
}

/**
 * getUserRegistrationDetails (auto-injected with server client)
 */
export async function getUserRegistrationDetails(
  ...args: Parameters<typeof getUserRegistrationDetails_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserRegistrationDetails_core>>> {
  const client = await createServerSupabaseClient();
  return getUserRegistrationDetails_core(client, ...args);
}

/**
 * getTournamentPhases (auto-injected with server client)
 */
export async function getTournamentPhases(
  ...args: Parameters<typeof getTournamentPhases_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentPhases_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentPhases_core(client, ...args);
}

/**
 * getTournamentRounds (auto-injected with server client)
 */
export async function getTournamentRounds(
  ...args: Parameters<typeof getTournamentRounds_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentRounds_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentRounds_core(client, ...args);
}

/**
 * getRoundMatches (auto-injected with server client)
 */
export async function getRoundMatches(
  ...args: Parameters<typeof getRoundMatches_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getRoundMatches_core>>> {
  const client = await createServerSupabaseClient();
  return getRoundMatches_core(client, ...args);
}

/**
 * getTournamentStandings (auto-injected with server client)
 */
export async function getTournamentStandings(
  ...args: Parameters<typeof getTournamentStandings_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentStandings_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentStandings_core(client, ...args);
}

/**
 * getPlayerTournamentStats (auto-injected with server client)
 */
export async function getPlayerTournamentStats(
  ...args: Parameters<typeof getPlayerTournamentStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerTournamentStats_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerTournamentStats_core(client, ...args);
}

/**
 * getTournamentPlayerStats (auto-injected with server client)
 */
export async function getTournamentPlayerStats(
  ...args: Parameters<typeof getTournamentPlayerStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentPlayerStats_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentPlayerStats_core(client, ...args);
}

/**
 * getPhaseRoundsWithStats (auto-injected with server client)
 */
export async function getPhaseRoundsWithStats(
  ...args: Parameters<typeof getPhaseRoundsWithStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPhaseRoundsWithStats_core>>> {
  const client = await createServerSupabaseClient();
  return getPhaseRoundsWithStats_core(client, ...args);
}

/**
 * getRoundMatchesWithStats (auto-injected with server client)
 */
export async function getRoundMatchesWithStats(
  ...args: Parameters<typeof getRoundMatchesWithStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getRoundMatchesWithStats_core>>> {
  const client = await createServerSupabaseClient();
  return getRoundMatchesWithStats_core(client, ...args);
}

/**
 * getPhaseRoundsWithMatches (auto-injected with server client)
 */
export async function getPhaseRoundsWithMatches(
  ...args: Parameters<typeof getPhaseRoundsWithMatches_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPhaseRoundsWithMatches_core>>> {
  const client = await createServerSupabaseClient();
  return getPhaseRoundsWithMatches_core(client, ...args);
}

/**
 * getCheckInStatus (auto-injected with server client)
 */
export async function getCheckInStatus(
  ...args: Parameters<typeof getCheckInStatus_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCheckInStatus_core>>> {
  const client = await createServerSupabaseClient();
  return getCheckInStatus_core(client, ...args);
}

/**
 * getCheckInStats (auto-injected with server client)
 */
export async function getCheckInStats(
  ...args: Parameters<typeof getCheckInStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCheckInStats_core>>> {
  const client = await createServerSupabaseClient();
  return getCheckInStats_core(client, ...args);
}

/**
 * getUserTeams (auto-injected with server client)
 */
export async function getUserTeams(
  ...args: Parameters<typeof getUserTeams_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserTeams_core>>> {
  const client = await createServerSupabaseClient();
  return getUserTeams_core(client, ...args);
}

/**
 * getMatchDetails (auto-injected with server client)
 */
export async function getMatchDetails(
  ...args: Parameters<typeof getMatchDetails_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchDetails_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchDetails_core(client, ...args);
}

/**
 * getMatchByRoundAndTable (auto-injected with server client)
 */
export async function getMatchByRoundAndTable(
  ...args: Parameters<typeof getMatchByRoundAndTable_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMatchByRoundAndTable_core>>> {
  const client = await createServerSupabaseClient();
  return getMatchByRoundAndTable_core(client, ...args);
}

/**
 * getPlayerMatches (auto-injected with server client)
 */
export async function getPlayerMatches(
  ...args: Parameters<typeof getPlayerMatches_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerMatches_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerMatches_core(client, ...args);
}

/**
 * getTournamentMatchesForStaff (auto-injected with server client)
 */
export async function getTournamentMatchesForStaff(
  ...args: Parameters<typeof getTournamentMatchesForStaff_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentMatchesForStaff_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentMatchesForStaff_core(client, ...args);
}

/**
 * getActiveMatch (auto-injected with server client)
 */
export async function getActiveMatch(
  ...args: Parameters<typeof getActiveMatch_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getActiveMatch_core>>> {
  const client = await createServerSupabaseClient();
  return getActiveMatch_core(client, ...args);
}

/**
 * getMyDashboardData (auto-injected with server client)
 */
export async function getMyDashboardData(
  ...args: Parameters<typeof getMyDashboardData_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getMyDashboardData_core>>> {
  const client = await createServerSupabaseClient();
  return getMyDashboardData_core(client, ...args);
}

/**
 * getRegistrationStatus (auto-injected with server client)
 */
export async function getRegistrationStatus(
  ...args: Parameters<typeof getRegistrationStatus_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getRegistrationStatus_core>>> {
  const client = await createServerSupabaseClient();
  return getRegistrationStatus_core(client, ...args);
}

/**
 * getTournamentInvitationsSent (auto-injected with server client)
 */
export async function getTournamentInvitationsSent(
  ...args: Parameters<typeof getTournamentInvitationsSent_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentInvitationsSent_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentInvitationsSent_core(client, ...args);
}

/**
 * getTournamentInvitationsReceived (auto-injected with server client)
 */
export async function getTournamentInvitationsReceived(
  ...args: Parameters<typeof getTournamentInvitationsReceived_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTournamentInvitationsReceived_core>>> {
  const client = await createServerSupabaseClient();
  return getTournamentInvitationsReceived_core(client, ...args);
}

/**
 * getTeamForRegistration (auto-injected with server client)
 */
export async function getTeamForRegistration(
  ...args: Parameters<typeof getTeamForRegistration_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getTeamForRegistration_core>>> {
  const client = await createServerSupabaseClient();
  return getTeamForRegistration_core(client, ...args);
}

/**
 * getUnpairedCheckedInPlayers (auto-injected with server client)
 */
export async function getUnpairedCheckedInPlayers(
  ...args: Parameters<typeof getUnpairedCheckedInPlayers_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUnpairedCheckedInPlayers_core>>> {
  const client = await createServerSupabaseClient();
  return getUnpairedCheckedInPlayers_core(client, ...args);
}

/**
 * getUserTournamentHistory (auto-injected with server client)
 */
export async function getUserTournamentHistory(
  ...args: Parameters<typeof getUserTournamentHistory_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserTournamentHistory_core>>> {
  const client = await createServerSupabaseClient();
  return getUserTournamentHistory_core(client, ...args);
}

/**
 * getPlayerTournamentHistory (auto-injected with server client)
 */
export async function getPlayerTournamentHistory(
  ...args: Parameters<typeof getPlayerTournamentHistory_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerTournamentHistory_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerTournamentHistory_core(client, ...args);
}

/**
 * getPlayerLifetimeStats (auto-injected with server client)
 */
export async function getPlayerLifetimeStats(
  ...args: Parameters<typeof getPlayerLifetimeStats_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerLifetimeStats_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerLifetimeStats_core(client, ...args);
}

/**
 * getUserCount (auto-injected with server client)
 */
export async function getUserCount(
  ...args: Parameters<typeof getUserCount_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserCount_core>>> {
  const client = await createServerSupabaseClient();
  return getUserCount_core(client, ...args);
}

/**
 * getCurrentUser (auto-injected with server client)
 */
export async function getCurrentUser(
  ...args: Parameters<typeof getCurrentUser_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCurrentUser_core>>> {
  const client = await createServerSupabaseClient();
  return getCurrentUser_core(client, ...args);
}

/**
 * getUserSpritePreference (auto-injected with server client)
 */
export async function getUserSpritePreference(
  ...args: Parameters<typeof getUserSpritePreference_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserSpritePreference_core>>> {
  const client = await createServerSupabaseClient();
  return getUserSpritePreference_core(client, ...args);
}

/**
 * getUserById (auto-injected with server client)
 */
export async function getUserById(
  ...args: Parameters<typeof getUserById_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserById_core>>> {
  const client = await createServerSupabaseClient();
  return getUserById_core(client, ...args);
}

/**
 * getUserWithAlt (auto-injected with server client)
 */
export async function getUserWithAlt(
  ...args: Parameters<typeof getUserWithAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getUserWithAlt_core>>> {
  const client = await createServerSupabaseClient();
  return getUserWithAlt_core(client, ...args);
}

/**
 * getAltByUsername (auto-injected with server client)
 */
export async function getAltByUsername(
  ...args: Parameters<typeof getAltByUsername_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getAltByUsername_core>>> {
  const client = await createServerSupabaseClient();
  return getAltByUsername_core(client, ...args);
}

/**
 * getAltByUserId (auto-injected with server client)
 */
export async function getAltByUserId(
  ...args: Parameters<typeof getAltByUserId_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getAltByUserId_core>>> {
  const client = await createServerSupabaseClient();
  return getAltByUserId_core(client, ...args);
}

/**
 * getAltsByUserId (auto-injected with server client)
 */
export async function getAltsByUserId(
  ...args: Parameters<typeof getAltsByUserId_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getAltsByUserId_core>>> {
  const client = await createServerSupabaseClient();
  return getAltsByUserId_core(client, ...args);
}

/**
 * getCurrentUserAlts (auto-injected with server client)
 */
export async function getCurrentUserAlts(
  ...args: Parameters<typeof getCurrentUserAlts_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getCurrentUserAlts_core>>> {
  const client = await createServerSupabaseClient();
  return getCurrentUserAlts_core(client, ...args);
}

/**
 * searchAlts (auto-injected with server client)
 */
export async function searchAlts(
  ...args: Parameters<typeof searchAlts_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof searchAlts_core>>> {
  const client = await createServerSupabaseClient();
  return searchAlts_core(client, ...args);
}

/**
 * getPlayerProfileByHandle (auto-injected with server client)
 */
export async function getPlayerProfileByHandle(
  ...args: Parameters<typeof getPlayerProfileByHandle_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerProfileByHandle_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerProfileByHandle_core(client, ...args);
}

/**
 * getEmailByUsername (auto-injected with server client)
 */
export async function getEmailByUsername(
  ...args: Parameters<typeof getEmailByUsername_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getEmailByUsername_core>>> {
  const client = await createServerSupabaseClient();
  return getEmailByUsername_core(client, ...args);
}

/**
 * getFollowerCount (auto-injected with server client)
 */
export async function getFollowerCount(
  ...args: Parameters<typeof getFollowerCount_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getFollowerCount_core>>> {
  const client = await createServerSupabaseClient();
  return getFollowerCount_core(client, ...args);
}

/**
 * getFollowingCount (auto-injected with server client)
 */
export async function getFollowingCount(
  ...args: Parameters<typeof getFollowingCount_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getFollowingCount_core>>> {
  const client = await createServerSupabaseClient();
  return getFollowingCount_core(client, ...args);
}

/**
 * getPlayerTournamentHistoryFull (auto-injected with server client)
 */
export async function getPlayerTournamentHistoryFull(
  ...args: Parameters<typeof getPlayerTournamentHistoryFull_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerTournamentHistoryFull_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerTournamentHistoryFull_core(client, ...args);
}

/**
 * getPlayerPublicTeams (auto-injected with server client)
 */
export async function getPlayerPublicTeams(
  ...args: Parameters<typeof getPlayerPublicTeams_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof getPlayerPublicTeams_core>>> {
  const client = await createServerSupabaseClient();
  return getPlayerPublicTeams_core(client, ...args);
}

/**
 * submitGameSelection (auto-injected with server client)
 */
export async function submitGameSelection(
  ...args: Parameters<typeof submitGameSelection_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof submitGameSelection_core>>> {
  const client = await createServerSupabaseClient();
  return submitGameSelection_core(client, ...args);
}

/**
 * sendMatchMessage (auto-injected with server client)
 */
export async function sendMatchMessage(
  ...args: Parameters<typeof sendMatchMessage_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof sendMatchMessage_core>>> {
  const client = await createServerSupabaseClient();
  return sendMatchMessage_core(client, ...args);
}

/**
 * sendSystemMessage (auto-injected with server client)
 */
export async function sendSystemMessage(
  ...args: Parameters<typeof sendSystemMessage_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof sendSystemMessage_core>>> {
  const client = await createServerSupabaseClient();
  return sendSystemMessage_core(client, ...args);
}

/**
 * createMatchGames (auto-injected with server client)
 */
export async function createMatchGames(
  ...args: Parameters<typeof createMatchGames_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createMatchGames_core>>> {
  const client = await createServerSupabaseClient();
  return createMatchGames_core(client, ...args);
}

/**
 * judgeOverrideGame (auto-injected with server client)
 */
export async function judgeOverrideGame(
  ...args: Parameters<typeof judgeOverrideGame_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof judgeOverrideGame_core>>> {
  const client = await createServerSupabaseClient();
  return judgeOverrideGame_core(client, ...args);
}

/**
 * judgeResetGame (auto-injected with server client)
 */
export async function judgeResetGame(
  ...args: Parameters<typeof judgeResetGame_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof judgeResetGame_core>>> {
  const client = await createServerSupabaseClient();
  return judgeResetGame_core(client, ...args);
}

/**
 * resetMatch (auto-injected with server client)
 */
export async function resetMatch(
  ...args: Parameters<typeof resetMatch_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof resetMatch_core>>> {
  const client = await createServerSupabaseClient();
  return resetMatch_core(client, ...args);
}

/**
 * confirmMatchCheckIn (auto-injected with server client)
 */
export async function confirmMatchCheckIn(
  ...args: Parameters<typeof confirmMatchCheckIn_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof confirmMatchCheckIn_core>>> {
  const client = await createServerSupabaseClient();
  return confirmMatchCheckIn_core(client, ...args);
}

/**
 * upsertNotificationPreferences (auto-injected with server client)
 */
export async function upsertNotificationPreferences(
  ...args: Parameters<typeof upsertNotificationPreferences_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof upsertNotificationPreferences_core>>> {
  const client = await createServerSupabaseClient();
  return upsertNotificationPreferences_core(client, ...args);
}

/**
 * markNotificationRead (auto-injected with server client)
 */
export async function markNotificationRead(
  ...args: Parameters<typeof markNotificationRead_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof markNotificationRead_core>>> {
  const client = await createServerSupabaseClient();
  return markNotificationRead_core(client, ...args);
}

/**
 * markAllNotificationsRead (auto-injected with server client)
 */
export async function markAllNotificationsRead(
  ...args: Parameters<typeof markAllNotificationsRead_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof markAllNotificationsRead_core>>> {
  const client = await createServerSupabaseClient();
  return markAllNotificationsRead_core(client, ...args);
}

/**
 * deleteNotification (auto-injected with server client)
 */
export async function deleteNotification(
  ...args: Parameters<typeof deleteNotification_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteNotification_core>>> {
  const client = await createServerSupabaseClient();
  return deleteNotification_core(client, ...args);
}

/**
 * submitCommunityRequest (auto-injected with server client)
 */
export async function submitCommunityRequest(
  ...args: Parameters<typeof submitCommunityRequest_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof submitCommunityRequest_core>>> {
  const client = await createServerSupabaseClient();
  return submitCommunityRequest_core(client, ...args);
}

/**
 * approveCommunityRequest (auto-injected with server client)
 */
export async function approveCommunityRequest(
  ...args: Parameters<typeof approveCommunityRequest_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof approveCommunityRequest_core>>> {
  const client = await createServerSupabaseClient();
  return approveCommunityRequest_core(client, ...args);
}

/**
 * rejectCommunityRequest (auto-injected with server client)
 */
export async function rejectCommunityRequest(
  ...args: Parameters<typeof rejectCommunityRequest_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof rejectCommunityRequest_core>>> {
  const client = await createServerSupabaseClient();
  return rejectCommunityRequest_core(client, ...args);
}

/**
 * createCommunity (auto-injected with server client)
 */
export async function createCommunity(
  ...args: Parameters<typeof createCommunity_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createCommunity_core>>> {
  const client = await createServerSupabaseClient();
  return createCommunity_core(client, ...args);
}

/**
 * updateCommunity (auto-injected with server client)
 */
export async function updateCommunity(
  ...args: Parameters<typeof updateCommunity_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateCommunity_core>>> {
  const client = await createServerSupabaseClient();
  return updateCommunity_core(client, ...args);
}

/**
 * inviteToCommunity (auto-injected with server client)
 */
export async function inviteToCommunity(
  ...args: Parameters<typeof inviteToCommunity_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof inviteToCommunity_core>>> {
  const client = await createServerSupabaseClient();
  return inviteToCommunity_core(client, ...args);
}

/**
 * acceptCommunityInvitation (auto-injected with server client)
 */
export async function acceptCommunityInvitation(
  ...args: Parameters<typeof acceptCommunityInvitation_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof acceptCommunityInvitation_core>>> {
  const client = await createServerSupabaseClient();
  return acceptCommunityInvitation_core(client, ...args);
}

/**
 * declineCommunityInvitation (auto-injected with server client)
 */
export async function declineCommunityInvitation(
  ...args: Parameters<typeof declineCommunityInvitation_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof declineCommunityInvitation_core>>> {
  const client = await createServerSupabaseClient();
  return declineCommunityInvitation_core(client, ...args);
}

/**
 * leaveCommunity (auto-injected with server client)
 */
export async function leaveCommunity(
  ...args: Parameters<typeof leaveCommunity_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof leaveCommunity_core>>> {
  const client = await createServerSupabaseClient();
  return leaveCommunity_core(client, ...args);
}

/**
 * removeStaff (auto-injected with server client)
 */
export async function removeStaff(
  ...args: Parameters<typeof removeStaff_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof removeStaff_core>>> {
  const client = await createServerSupabaseClient();
  return removeStaff_core(client, ...args);
}

/**
 * addStaffMember (auto-injected with server client)
 */
export async function addStaffMember(
  ...args: Parameters<typeof addStaffMember_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof addStaffMember_core>>> {
  const client = await createServerSupabaseClient();
  return addStaffMember_core(client, ...args);
}

/**
 * addStaffToGroup (auto-injected with server client)
 */
export async function addStaffToGroup(
  ...args: Parameters<typeof addStaffToGroup_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof addStaffToGroup_core>>> {
  const client = await createServerSupabaseClient();
  return addStaffToGroup_core(client, ...args);
}

/**
 * removeStaffFromGroup (auto-injected with server client)
 */
export async function removeStaffFromGroup(
  ...args: Parameters<typeof removeStaffFromGroup_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof removeStaffFromGroup_core>>> {
  const client = await createServerSupabaseClient();
  return removeStaffFromGroup_core(client, ...args);
}

/**
 * changeStaffRole (auto-injected with server client)
 */
export async function changeStaffRole(
  ...args: Parameters<typeof changeStaffRole_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof changeStaffRole_core>>> {
  const client = await createServerSupabaseClient();
  return changeStaffRole_core(client, ...args);
}

/**
 * removeStaffCompletely (auto-injected with server client)
 */
export async function removeStaffCompletely(
  ...args: Parameters<typeof removeStaffCompletely_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof removeStaffCompletely_core>>> {
  const client = await createServerSupabaseClient();
  return removeStaffCompletely_core(client, ...args);
}

/**
 * updateAlt (auto-injected with server client)
 */
export async function updateAlt(
  ...args: Parameters<typeof updateAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateAlt_core>>> {
  const client = await createServerSupabaseClient();
  return updateAlt_core(client, ...args);
}

/**
 * updateUsername (auto-injected with server client)
 */
export async function updateUsername(
  ...args: Parameters<typeof updateUsername_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateUsername_core>>> {
  const client = await createServerSupabaseClient();
  return updateUsername_core(client, ...args);
}

/**
 * ensureAlt (auto-injected with server client)
 */
export async function ensureAlt(
  ...args: Parameters<typeof ensureAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof ensureAlt_core>>> {
  const client = await createServerSupabaseClient();
  return ensureAlt_core(client, ...args);
}

/**
 * createAlt (auto-injected with server client)
 */
export async function createAlt(
  ...args: Parameters<typeof createAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createAlt_core>>> {
  const client = await createServerSupabaseClient();
  return createAlt_core(client, ...args);
}

/**
 * deleteAlt (auto-injected with server client)
 */
export async function deleteAlt(
  ...args: Parameters<typeof deleteAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteAlt_core>>> {
  const client = await createServerSupabaseClient();
  return deleteAlt_core(client, ...args);
}

/**
 * setMainAlt (auto-injected with server client)
 */
export async function setMainAlt(
  ...args: Parameters<typeof setMainAlt_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof setMainAlt_core>>> {
  const client = await createServerSupabaseClient();
  return setMainAlt_core(client, ...args);
}

/**
 * startMatch (auto-injected with server client)
 */
export async function startMatch(
  ...args: Parameters<typeof startMatch_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof startMatch_core>>> {
  const client = await createServerSupabaseClient();
  return startMatch_core(client, ...args);
}

/**
 * reportMatchResult (auto-injected with server client)
 */
export async function reportMatchResult(
  ...args: Parameters<typeof reportMatchResult_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof reportMatchResult_core>>> {
  const client = await createServerSupabaseClient();
  return reportMatchResult_core(client, ...args);
}

/**
 * updatePhase (auto-injected with server client)
 */
export async function updatePhase(
  ...args: Parameters<typeof updatePhase_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updatePhase_core>>> {
  const client = await createServerSupabaseClient();
  return updatePhase_core(client, ...args);
}

/**
 * createPhase (auto-injected with server client)
 */
export async function createPhase(
  ...args: Parameters<typeof createPhase_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createPhase_core>>> {
  const client = await createServerSupabaseClient();
  return createPhase_core(client, ...args);
}

/**
 * deletePhase (auto-injected with server client)
 */
export async function deletePhase(
  ...args: Parameters<typeof deletePhase_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deletePhase_core>>> {
  const client = await createServerSupabaseClient();
  return deletePhase_core(client, ...args);
}

/**
 * saveTournamentPhases (auto-injected with server client)
 */
export async function saveTournamentPhases(
  ...args: Parameters<typeof saveTournamentPhases_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof saveTournamentPhases_core>>> {
  const client = await createServerSupabaseClient();
  return saveTournamentPhases_core(client, ...args);
}

/**
 * registerForTournament (auto-injected with server client)
 */
export async function registerForTournament(
  ...args: Parameters<typeof registerForTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof registerForTournament_core>>> {
  const client = await createServerSupabaseClient();
  return registerForTournament_core(client, ...args);
}

/**
 * updateRegistrationPreferences (auto-injected with server client)
 */
export async function updateRegistrationPreferences(
  ...args: Parameters<typeof updateRegistrationPreferences_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateRegistrationPreferences_core>>> {
  const client = await createServerSupabaseClient();
  return updateRegistrationPreferences_core(client, ...args);
}

/**
 * cancelRegistration (auto-injected with server client)
 */
export async function cancelRegistration(
  ...args: Parameters<typeof cancelRegistration_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof cancelRegistration_core>>> {
  const client = await createServerSupabaseClient();
  return cancelRegistration_core(client, ...args);
}

/**
 * updateRegistrationStatus (auto-injected with server client)
 */
export async function updateRegistrationStatus(
  ...args: Parameters<typeof updateRegistrationStatus_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateRegistrationStatus_core>>> {
  const client = await createServerSupabaseClient();
  return updateRegistrationStatus_core(client, ...args);
}

/**
 * checkIn (auto-injected with server client)
 */
export async function checkIn(
  ...args: Parameters<typeof checkIn_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof checkIn_core>>> {
  const client = await createServerSupabaseClient();
  return checkIn_core(client, ...args);
}

/**
 * undoCheckIn (auto-injected with server client)
 */
export async function undoCheckIn(
  ...args: Parameters<typeof undoCheckIn_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof undoCheckIn_core>>> {
  const client = await createServerSupabaseClient();
  return undoCheckIn_core(client, ...args);
}

/**
 * withdrawFromTournament (auto-injected with server client)
 */
export async function withdrawFromTournament(
  ...args: Parameters<typeof withdrawFromTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof withdrawFromTournament_core>>> {
  const client = await createServerSupabaseClient();
  return withdrawFromTournament_core(client, ...args);
}

/**
 * sendTournamentInvitations (auto-injected with server client)
 */
export async function sendTournamentInvitations(
  ...args: Parameters<typeof sendTournamentInvitations_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof sendTournamentInvitations_core>>> {
  const client = await createServerSupabaseClient();
  return sendTournamentInvitations_core(client, ...args);
}

/**
 * respondToTournamentInvitation (auto-injected with server client)
 */
export async function respondToTournamentInvitation(
  ...args: Parameters<typeof respondToTournamentInvitation_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof respondToTournamentInvitation_core>>> {
  const client = await createServerSupabaseClient();
  return respondToTournamentInvitation_core(client, ...args);
}

/**
 * generateRoundPairings (auto-injected with server client)
 */
export async function generateRoundPairings(
  ...args: Parameters<typeof generateRoundPairings_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof generateRoundPairings_core>>> {
  const client = await createServerSupabaseClient();
  return generateRoundPairings_core(client, ...args);
}

/**
 * startRound (auto-injected with server client)
 */
export async function startRound(
  ...args: Parameters<typeof startRound_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof startRound_core>>> {
  const client = await createServerSupabaseClient();
  return startRound_core(client, ...args);
}

/**
 * completeRound (auto-injected with server client)
 */
export async function completeRound(
  ...args: Parameters<typeof completeRound_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof completeRound_core>>> {
  const client = await createServerSupabaseClient();
  return completeRound_core(client, ...args);
}

/**
 * createRound (auto-injected with server client)
 */
export async function createRound(
  ...args: Parameters<typeof createRound_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createRound_core>>> {
  const client = await createServerSupabaseClient();
  return createRound_core(client, ...args);
}

/**
 * deleteRoundAndMatches (auto-injected with server client)
 */
export async function deleteRoundAndMatches(
  ...args: Parameters<typeof deleteRoundAndMatches_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteRoundAndMatches_core>>> {
  const client = await createServerSupabaseClient();
  return deleteRoundAndMatches_core(client, ...args);
}

/**
 * recalculateStandings (auto-injected with server client)
 */
export async function recalculateStandings(
  ...args: Parameters<typeof recalculateStandings_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof recalculateStandings_core>>> {
  const client = await createServerSupabaseClient();
  return recalculateStandings_core(client, ...args);
}

/**
 * dropPlayer (auto-injected with server client)
 */
export async function dropPlayer(
  ...args: Parameters<typeof dropPlayer_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof dropPlayer_core>>> {
  const client = await createServerSupabaseClient();
  return dropPlayer_core(client, ...args);
}

/**
 * submitTeam (auto-injected with server client)
 */
export async function submitTeam(
  ...args: Parameters<typeof submitTeam_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof submitTeam_core>>> {
  const client = await createServerSupabaseClient();
  return submitTeam_core(client, ...args);
}

/**
 * selectTeamForTournament (auto-injected with server client)
 */
export async function selectTeamForTournament(
  ...args: Parameters<typeof selectTeamForTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof selectTeamForTournament_core>>> {
  const client = await createServerSupabaseClient();
  return selectTeamForTournament_core(client, ...args);
}

/**
 * createTournament (auto-injected with server client)
 */
export async function createTournament(
  ...args: Parameters<typeof createTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof createTournament_core>>> {
  const client = await createServerSupabaseClient();
  return createTournament_core(client, ...args);
}

/**
 * updateTournament (auto-injected with server client)
 */
export async function updateTournament(
  ...args: Parameters<typeof updateTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof updateTournament_core>>> {
  const client = await createServerSupabaseClient();
  return updateTournament_core(client, ...args);
}

/**
 * archiveTournament (auto-injected with server client)
 */
export async function archiveTournament(
  ...args: Parameters<typeof archiveTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof archiveTournament_core>>> {
  const client = await createServerSupabaseClient();
  return archiveTournament_core(client, ...args);
}

/**
 * deleteTournament (auto-injected with server client)
 */
export async function deleteTournament(
  ...args: Parameters<typeof deleteTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof deleteTournament_core>>> {
  const client = await createServerSupabaseClient();
  return deleteTournament_core(client, ...args);
}

/**
 * startTournamentEnhanced (auto-injected with server client)
 */
export async function startTournamentEnhanced(
  ...args: Parameters<typeof startTournamentEnhanced_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof startTournamentEnhanced_core>>> {
  const client = await createServerSupabaseClient();
  return startTournamentEnhanced_core(client, ...args);
}

/**
 * advanceToTopCut (auto-injected with server client)
 */
export async function advanceToTopCut(
  ...args: Parameters<typeof advanceToTopCut_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof advanceToTopCut_core>>> {
  const client = await createServerSupabaseClient();
  return advanceToTopCut_core(client, ...args);
}

/**
 * generateEliminationPairings (auto-injected with server client)
 */
export async function generateEliminationPairings(
  ...args: Parameters<typeof generateEliminationPairings_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof generateEliminationPairings_core>>> {
  const client = await createServerSupabaseClient();
  return generateEliminationPairings_core(client, ...args);
}

/**
 * completeTournament (auto-injected with server client)
 */
export async function completeTournament(
  ...args: Parameters<typeof completeTournament_core> extends [
    first: infer _F,
    ...rest: infer R,
  ]
    ? R
    : never
): Promise<Awaited<ReturnType<typeof completeTournament_core>>> {
  const client = await createServerSupabaseClient();
  return completeTournament_core(client, ...args);
}
