-- =============================================================================
-- trainers.gg Local Development Seed Data
-- =============================================================================
-- This file creates test data for local development.
-- It runs automatically after migrations via `supabase db reset`.
--
-- IMPORTANT: This file should NEVER be used in production.
-- =============================================================================

-- Enable pgcrypto for password hashing
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- -----------------------------------------------------------------------------
-- Fixed UUIDs for test data (makes it easy to reference in tests)
-- -----------------------------------------------------------------------------
-- Users:     11111111-1111-1111-1111-11111111111X  (auth.users IDs)
-- Profiles:  Generated by trigger (we look them up after)
-- Orgs:      aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaX
-- Pokemon:   a0000001-0001-0001-0001-00000000000X (Ash's)
--            b0000002-0002-0002-0002-00000000000X (Cynthia's)
--            c0000003-0003-0003-0003-00000000000X (Meta)
-- Teams:     d0000001-0001-0001-0001-00000000000X
-- Tournaments: e0000001-0001-0001-0001-00000000000X

-- -----------------------------------------------------------------------------
-- Test Users (via auth.users - trigger creates public.users + profiles)
-- -----------------------------------------------------------------------------

INSERT INTO auth.users (
  id, instance_id, email, encrypted_password, email_confirmed_at,
  raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) VALUES
  ('11111111-1111-1111-1111-111111111111', '00000000-0000-0000-0000-000000000000',
   'admin@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "admin_trainer", "name": "Admin Trainer"}'::jsonb, NOW(), NOW(), '', '', '', ''),
  
  ('11111111-1111-1111-1111-111111111112', '00000000-0000-0000-0000-000000000000',
   'player@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "ash_ketchum", "name": "Ash Ketchum"}'::jsonb, NOW(), NOW(), '', '', '', ''),
  
  ('11111111-1111-1111-1111-111111111113', '00000000-0000-0000-0000-000000000000',
   'champion@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "cynthia", "name": "Cynthia"}'::jsonb, NOW(), NOW(), '', '', '', ''),
  
  ('11111111-1111-1111-1111-111111111114', '00000000-0000-0000-0000-000000000000',
   'gymleader@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "brock", "name": "Brock"}'::jsonb, NOW(), NOW(), '', '', '', ''),
  
  ('11111111-1111-1111-1111-111111111115', '00000000-0000-0000-0000-000000000000',
   'elite@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "karen", "name": "Karen"}'::jsonb, NOW(), NOW(), '', '', '', ''),
  
  ('11111111-1111-1111-1111-111111111116', '00000000-0000-0000-0000-000000000000',
   'casual@trainers.local', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(),
   '{"username": "red", "name": "Red"}'::jsonb, NOW(), NOW(), '', '', '', '');

-- -----------------------------------------------------------------------------
-- Update users/profiles with additional data (trigger created basic records)
-- -----------------------------------------------------------------------------

UPDATE public.users SET
  first_name = 'Admin', last_name = 'Trainer', birth_date = '1990-01-15', country = 'US'
WHERE id = '11111111-1111-1111-1111-111111111111';

UPDATE public.users SET
  first_name = 'Ash', last_name = 'Ketchum', birth_date = '1997-05-22', country = 'JP'
WHERE id = '11111111-1111-1111-1111-111111111112';

UPDATE public.users SET
  first_name = 'Cynthia', last_name = 'Shirona', birth_date = '1985-07-10', country = 'JP'
WHERE id = '11111111-1111-1111-1111-111111111113';

UPDATE public.users SET
  first_name = 'Brock', last_name = 'Harrison', birth_date = '1992-03-08', country = 'JP'
WHERE id = '11111111-1111-1111-1111-111111111114';

UPDATE public.users SET
  first_name = 'Karen', last_name = 'Elite', birth_date = '1988-11-30', country = 'JP'
WHERE id = '11111111-1111-1111-1111-111111111115';

UPDATE public.users SET
  first_name = 'Red', last_name = 'Champion', birth_date = '1996-08-27', country = 'JP'
WHERE id = '11111111-1111-1111-1111-111111111116';

-- Update profiles with bios and tiers
UPDATE public.profiles SET
  bio = 'Platform administrator and VGC enthusiast. Organizing tournaments since 2015.'
WHERE user_id = '11111111-1111-1111-1111-111111111111';

UPDATE public.profiles SET
  bio = 'Gotta catch em all! On my journey to become a Pokemon Master.',
  tier = 'player_pro'
WHERE user_id = '11111111-1111-1111-1111-111111111112';

UPDATE public.profiles SET
  bio = 'Sinnoh Champion. I believe the bonds we share with Pokemon lead to true strength.',
  tier = 'player_pro'
WHERE user_id = '11111111-1111-1111-1111-111111111113';

UPDATE public.profiles SET
  bio = 'Pewter City Gym Leader. Rock-type specialist and Pokemon Breeder.'
WHERE user_id = '11111111-1111-1111-1111-111111111114';

UPDATE public.profiles SET
  bio = 'Elite Four member. Strong Pokemon. Weak Pokemon. That is only the selfish perception of people.'
WHERE user_id = '11111111-1111-1111-1111-111111111115';

UPDATE public.profiles SET
  bio = '...'
WHERE user_id = '11111111-1111-1111-1111-111111111116';

-- -----------------------------------------------------------------------------
-- Organizations (use DO block to look up profile IDs from trigger)
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  admin_profile_id uuid;
  ash_profile_id uuid;
  cynthia_profile_id uuid;
BEGIN
  -- Get profile IDs created by trigger
  SELECT id INTO admin_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111111';
  SELECT id INTO ash_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111112';
  SELECT id INTO cynthia_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111113';

  -- Organizations
  INSERT INTO public.organizations (
    id, name, slug, description, status, owner_profile_id, tier, subscription_tier,
    discord_url, twitter_url, website_url
  ) VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
     'VGC League', 'vgc-league',
     'Premier Pokemon VGC tournament organization. Weekly locals and monthly championships.',
     'active', admin_profile_id, 'partner', 'organization_plus',
     'https://discord.gg/vgcleague', 'https://twitter.com/vgcleague', 'https://vgcleague.com'),
    
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab',
     'Pallet Town Trainers', 'pallet-town',
     'A friendly community for trainers from Pallet Town and beyond. Casual and competitive events.',
     'active', ash_profile_id, 'regular', 'free',
     NULL, NULL, NULL),
    
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac',
     'Sinnoh Champions', 'sinnoh-champions',
     'Elite tournament series for Sinnoh region trainers. High-level competitive play.',
     'active', cynthia_profile_id, 'verified', 'organization_plus',
     'https://discord.gg/sinnoh', NULL, NULL);

  -- Organization members
  INSERT INTO public.organization_members (organization_id, profile_id) VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', admin_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', ash_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', cynthia_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab', ash_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab', admin_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac', cynthia_profile_id),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac', admin_profile_id);
END $$;

-- -----------------------------------------------------------------------------
-- Pokemon (sample competitive Pokemon)
-- -----------------------------------------------------------------------------

INSERT INTO public.pokemon (
  id, species, nickname, nature, ability, held_item, gender, is_shiny,
  move1, move2, move3, move4,
  ev_hp, ev_attack, ev_defense, ev_special_attack, ev_special_defense, ev_speed,
  tera_type
) VALUES
  -- Ash's Team
  ('a0000001-0001-0001-0001-000000000001', 'Pikachu', 'Pika', 'Timid', 'Static', 'Light Ball', 'Male', false,
   'Thunderbolt', 'Volt Tackle', 'Iron Tail', 'Quick Attack', 0, 0, 0, 252, 4, 252, 'Electric'),
  ('a0000001-0001-0001-0001-000000000002', 'Charizard', NULL, 'Timid', 'Solar Power', 'Choice Specs', 'Male', false,
   'Heat Wave', 'Air Slash', 'Dragon Pulse', 'Protect', 0, 0, 0, 252, 4, 252, 'Fire'),
  ('a0000001-0001-0001-0001-000000000003', 'Greninja', NULL, 'Timid', 'Protean', 'Focus Sash', 'Male', false,
   'Hydro Pump', 'Ice Beam', 'Dark Pulse', 'Protect', 0, 0, 0, 252, 4, 252, 'Water'),
  ('a0000001-0001-0001-0001-000000000004', 'Lucario', NULL, 'Jolly', 'Inner Focus', 'Life Orb', 'Male', false,
   'Close Combat', 'Extreme Speed', 'Bullet Punch', 'Swords Dance', 0, 252, 0, 0, 4, 252, 'Fighting'),
  ('a0000001-0001-0001-0001-000000000005', 'Dragonite', NULL, 'Adamant', 'Multiscale', 'Leftovers', 'Male', false,
   'Dragon Dance', 'Outrage', 'Extreme Speed', 'Earthquake', 252, 252, 0, 0, 4, 0, 'Normal'),
  ('a0000001-0001-0001-0001-000000000006', 'Snorlax', NULL, 'Careful', 'Thick Fat', 'Leftovers', 'Male', false,
   'Body Slam', 'Crunch', 'Curse', 'Rest', 252, 0, 0, 0, 252, 4, 'Normal'),

  -- Cynthia's Team
  ('b0000002-0002-0002-0002-000000000001', 'Garchomp', NULL, 'Jolly', 'Rough Skin', 'Rocky Helmet', 'Female', false,
   'Earthquake', 'Dragon Claw', 'Swords Dance', 'Protect', 0, 252, 0, 0, 4, 252, 'Ground'),
  ('b0000002-0002-0002-0002-000000000002', 'Spiritomb', NULL, 'Bold', 'Pressure', 'Sitrus Berry', 'Female', false,
   'Shadow Ball', 'Dark Pulse', 'Will-O-Wisp', 'Pain Split', 252, 0, 252, 0, 4, 0, 'Ghost'),
  ('b0000002-0002-0002-0002-000000000003', 'Lucario', NULL, 'Modest', 'Steadfast', 'Choice Specs', 'Male', false,
   'Aura Sphere', 'Flash Cannon', 'Vacuum Wave', 'Dragon Pulse', 0, 0, 0, 252, 4, 252, 'Steel'),
  ('b0000002-0002-0002-0002-000000000004', 'Togekiss', NULL, 'Timid', 'Serene Grace', 'Scope Lens', 'Female', false,
   'Air Slash', 'Dazzling Gleam', 'Follow Me', 'Protect', 252, 0, 0, 252, 4, 0, 'Fairy'),
  ('b0000002-0002-0002-0002-000000000005', 'Milotic', NULL, 'Bold', 'Marvel Scale', 'Flame Orb', 'Female', false,
   'Scald', 'Ice Beam', 'Recover', 'Protect', 252, 0, 252, 0, 4, 0, 'Water'),
  ('b0000002-0002-0002-0002-000000000006', 'Roserade', NULL, 'Timid', 'Natural Cure', 'Focus Sash', 'Female', false,
   'Leaf Storm', 'Sludge Bomb', 'Sleep Powder', 'Protect', 0, 0, 0, 252, 4, 252, 'Grass'),

  -- Sample Meta Pokemon (Reg G)
  ('c0000003-0003-0003-0003-000000000001', 'Flutter Mane', NULL, 'Timid', 'Protosynthesis', 'Booster Energy', NULL, false,
   'Shadow Ball', 'Moonblast', 'Dazzling Gleam', 'Protect', 0, 0, 0, 252, 4, 252, 'Fairy'),
  ('c0000003-0003-0003-0003-000000000002', 'Koraidon', NULL, 'Adamant', 'Orichalcum Pulse', 'Clear Amulet', NULL, false,
   'Collision Course', 'Flare Blitz', 'Dragon Claw', 'Protect', 0, 252, 0, 0, 4, 252, 'Fighting'),
  ('c0000003-0003-0003-0003-000000000003', 'Miraidon', NULL, 'Timid', 'Hadron Engine', 'Choice Specs', NULL, false,
   'Electro Drift', 'Draco Meteor', 'Volt Switch', 'Thunder', 0, 0, 0, 252, 4, 252, 'Electric'),
  ('c0000003-0003-0003-0003-000000000004', 'Rillaboom', NULL, 'Adamant', 'Grassy Surge', 'Miracle Seed', 'Male', false,
   'Grassy Glide', 'Wood Hammer', 'U-turn', 'Fake Out', 252, 252, 0, 0, 4, 0, 'Grass'),
  ('c0000003-0003-0003-0003-000000000005', 'Incineroar', NULL, 'Careful', 'Intimidate', 'Safety Goggles', 'Male', false,
   'Flare Blitz', 'Knock Off', 'Fake Out', 'Parting Shot', 252, 0, 0, 0, 252, 4, 'Dark'),
  ('c0000003-0003-0003-0003-000000000006', 'Amoonguss', NULL, 'Relaxed', 'Regenerator', 'Rocky Helmet', NULL, false,
   'Spore', 'Pollen Puff', 'Rage Powder', 'Protect', 252, 0, 252, 0, 4, 0, 'Grass');

-- -----------------------------------------------------------------------------
-- Teams
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  admin_profile_id uuid;
  ash_profile_id uuid;
  cynthia_profile_id uuid;
BEGIN
  SELECT id INTO admin_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111111';
  SELECT id INTO ash_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111112';
  SELECT id INTO cynthia_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111113';

  INSERT INTO public.teams (id, name, description, created_by, is_public, tags, notes) VALUES
    ('d0000001-0001-0001-0001-000000000001', 'Kanto Classics',
     'My journey team, now VGC ready!', ash_profile_id,
     true, ARRAY['VGC', 'Kanto', 'Offensive'], 'Featured on stream at Worlds 2024'),
    
    ('d0000002-0002-0002-0002-000000000002', 'Sinnoh Elite',
     'Championship team - balanced offense and defense', cynthia_profile_id,
     true, ARRAY['VGC', 'Sinnoh', 'Balance'], 'Undefeated at Sinnoh Regionals'),
    
    ('d0000003-0003-0003-0003-000000000003', 'Regulation G Meta',
     'Current meta sample team for testing', admin_profile_id,
     true, ARRAY['VGC', 'Reg G', 'Meta'], 'Sample team for local testing');
END $$;

-- Link Pokemon to Teams
INSERT INTO public.team_pokemon (team_id, pokemon_id, team_position) VALUES
  -- Ash's Team
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000001', 1),
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000002', 2),
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000003', 3),
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000004', 4),
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000005', 5),
  ('d0000001-0001-0001-0001-000000000001', 'a0000001-0001-0001-0001-000000000006', 6),
  -- Cynthia's Team
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000001', 1),
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000002', 2),
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000003', 3),
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000004', 4),
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000005', 5),
  ('d0000002-0002-0002-0002-000000000002', 'b0000002-0002-0002-0002-000000000006', 6),
  -- Meta Team
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000001', 1),
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000002', 2),
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000003', 3),
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000004', 4),
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000005', 5),
  ('d0000003-0003-0003-0003-000000000003', 'c0000003-0003-0003-0003-000000000006', 6);

-- -----------------------------------------------------------------------------
-- Tournaments
-- -----------------------------------------------------------------------------

INSERT INTO public.tournaments (
  id, organization_id, name, slug, description, format, status,
  start_date, end_date, registration_deadline, max_participants,
  tournament_format, swiss_rounds, round_time_minutes, featured, top_cut_size
) VALUES
  -- Upcoming weekly (VGC League)
  ('e0000001-0001-0001-0001-000000000001', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
   'VGC Weekly #42', 'vgc-weekly-42',
   'Weekly VGC tournament. Bo3 Swiss into Top 8 cut.',
   'VGC Regulation G', 'upcoming',
   NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '6 hours',
   NOW() + INTERVAL '2 days', 32,
   'swiss_with_cut', 5, 50, false, NULL),
  
  -- Active tournament (VGC League)
  ('e0000002-0002-0002-0002-000000000002', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
   'VGC Monthly Championship', 'vgc-monthly-jan',
   'Monthly championship series. Top 8 earns Championship Points!',
   'VGC Regulation G', 'active',
   NOW() - INTERVAL '2 hours', NOW() + INTERVAL '6 hours',
   NOW() - INTERVAL '1 day', 64,
   'swiss_with_cut', 6, 50, true, 8),
  
  -- Completed tournament (Sinnoh Champions)
  ('e0000003-0003-0003-0003-000000000003', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac',
   'Sinnoh Regional Qualifier', 'sinnoh-regional-q1',
   'Qualify for the Sinnoh Regional Championship!',
   'VGC Regulation G', 'completed',
   NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days' + INTERVAL '8 hours',
   NOW() - INTERVAL '8 days', 128,
   'swiss_with_cut', 7, 50, false, NULL),
  
  -- Draft tournament (Pallet Town)
  ('e0000004-0004-0004-0004-000000000004', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab',
   'Pallet Town Friendly', 'pallet-friendly-feb',
   'Casual tournament for beginners and experienced players alike!',
   'VGC Regulation G', 'draft',
   NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days' + INTERVAL '4 hours',
   NOW() + INTERVAL '13 days', 16,
   'swiss_only', NULL, 50, false, NULL);

-- -----------------------------------------------------------------------------
-- Tournament Registrations
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  ash_profile_id uuid;
  cynthia_profile_id uuid;
  brock_profile_id uuid;
  karen_profile_id uuid;
  red_profile_id uuid;
BEGIN
  SELECT id INTO ash_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111112';
  SELECT id INTO cynthia_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111113';
  SELECT id INTO brock_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111114';
  SELECT id INTO karen_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111115';
  SELECT id INTO red_profile_id FROM public.profiles WHERE user_id = '11111111-1111-1111-1111-111111111116';

  -- Registrations for upcoming tournament (Weekly #42)
  INSERT INTO public.tournament_registrations (tournament_id, profile_id, status, team_name) VALUES
    ('e0000001-0001-0001-0001-000000000001', ash_profile_id, 'registered', 'Kanto Classics'),
    ('e0000001-0001-0001-0001-000000000001', cynthia_profile_id, 'registered', 'Sinnoh Elite'),
    ('e0000001-0001-0001-0001-000000000001', brock_profile_id, 'registered', NULL),
    ('e0000001-0001-0001-0001-000000000001', karen_profile_id, 'pending', NULL);

  -- Registrations for active tournament (Monthly Championship)
  INSERT INTO public.tournament_registrations (tournament_id, profile_id, status, team_name, checked_in_at) VALUES
    ('e0000002-0002-0002-0002-000000000002', ash_profile_id, 'checked_in', 'Kanto Classics', NOW() - INTERVAL '3 hours'),
    ('e0000002-0002-0002-0002-000000000002', cynthia_profile_id, 'checked_in', 'Sinnoh Elite', NOW() - INTERVAL '2 hours'),
    ('e0000002-0002-0002-0002-000000000002', brock_profile_id, 'checked_in', NULL, NOW() - INTERVAL '2 hours'),
    ('e0000002-0002-0002-0002-000000000002', karen_profile_id, 'checked_in', NULL, NOW() - INTERVAL '1 hour'),
    ('e0000002-0002-0002-0002-000000000002', red_profile_id, 'checked_in', NULL, NOW() - INTERVAL '30 minutes');
END $$;

-- -----------------------------------------------------------------------------
-- Roles and Permissions (for RBAC)
-- -----------------------------------------------------------------------------

INSERT INTO public.roles (id, name, description) VALUES
  ('f0000001-0001-0001-0001-000000000001', 'Owner', 'Full control over the organization'),
  ('f0000002-0002-0002-0002-000000000002', 'Admin', 'Administrative privileges'),
  ('f0000003-0003-0003-0003-000000000003', 'Moderator', 'Can moderate content and users'),
  ('f0000004-0004-0004-0004-000000000004', 'Tournament Organizer', 'Can create and manage tournaments'),
  ('f0000005-0005-0005-0005-000000000005', 'Judge', 'Can resolve match disputes'),
  ('f0000006-0006-0006-0006-000000000006', 'Member', 'Basic member access');

INSERT INTO public.permissions (id, key, name, description) VALUES
  ('f1000001-0001-0001-0001-000000000001', 'org.manage', 'Manage Organization', 'Can modify organization settings'),
  ('f1000002-0002-0002-0002-000000000002', 'org.members.manage', 'Manage Members', 'Can add/remove organization members'),
  ('f1000003-0003-0003-0003-000000000003', 'tournament.create', 'Create Tournament', 'Can create new tournaments'),
  ('f1000004-0004-0004-0004-000000000004', 'tournament.manage', 'Manage Tournament', 'Can edit and manage tournaments'),
  ('f1000005-0005-0005-0005-000000000005', 'tournament.judge', 'Judge Matches', 'Can resolve match disputes'),
  ('f1000006-0006-0006-0006-000000000006', 'content.moderate', 'Moderate Content', 'Can moderate user content');

-- Link permissions to roles
INSERT INTO public.role_permissions (role_id, permission_id) VALUES
  -- Owner gets everything
  ('f0000001-0001-0001-0001-000000000001', 'f1000001-0001-0001-0001-000000000001'),
  ('f0000001-0001-0001-0001-000000000001', 'f1000002-0002-0002-0002-000000000002'),
  ('f0000001-0001-0001-0001-000000000001', 'f1000003-0003-0003-0003-000000000003'),
  ('f0000001-0001-0001-0001-000000000001', 'f1000004-0004-0004-0004-000000000004'),
  ('f0000001-0001-0001-0001-000000000001', 'f1000005-0005-0005-0005-000000000005'),
  ('f0000001-0001-0001-0001-000000000001', 'f1000006-0006-0006-0006-000000000006'),
  -- Admin gets most things
  ('f0000002-0002-0002-0002-000000000002', 'f1000002-0002-0002-0002-000000000002'),
  ('f0000002-0002-0002-0002-000000000002', 'f1000003-0003-0003-0003-000000000003'),
  ('f0000002-0002-0002-0002-000000000002', 'f1000004-0004-0004-0004-000000000004'),
  ('f0000002-0002-0002-0002-000000000002', 'f1000005-0005-0005-0005-000000000005'),
  ('f0000002-0002-0002-0002-000000000002', 'f1000006-0006-0006-0006-000000000006'),
  -- Moderator
  ('f0000003-0003-0003-0003-000000000003', 'f1000006-0006-0006-0006-000000000006'),
  -- Tournament Organizer
  ('f0000004-0004-0004-0004-000000000004', 'f1000003-0003-0003-0003-000000000003'),
  ('f0000004-0004-0004-0004-000000000004', 'f1000004-0004-0004-0004-000000000004'),
  -- Judge
  ('f0000005-0005-0005-0005-000000000005', 'f1000005-0005-0005-0005-000000000005');

-- =============================================================================
-- Seed Complete
-- =============================================================================
-- 
-- Test Accounts (all use password: password123)
-- 
-- | Email                    | Username       | Role          |
-- |--------------------------|----------------|---------------|
-- | admin@trainers.local     | admin_trainer  | Admin/Org     |
-- | player@trainers.local    | ash_ketchum    | Player Pro    |
-- | champion@trainers.local  | cynthia        | Player Pro    |
-- | gymleader@trainers.local | brock          | Regular       |
-- | elite@trainers.local     | karen          | Regular       |
-- | casual@trainers.local    | red            | Regular       |
--
-- Organizations:
-- - VGC League (partner tier, org_plus subscription)
-- - Pallet Town Trainers (regular tier, free)
-- - Sinnoh Champions (verified tier, org_plus subscription)
--
-- Tournaments:
-- - VGC Weekly #42 (upcoming)
-- - VGC Monthly Championship (active)
-- - Sinnoh Regional Qualifier (completed)
-- - Pallet Town Friendly (draft)
--
-- =============================================================================
