-- =============================================================================
-- 01_extensions.sql - Enable Required Extensions
-- =============================================================================
-- NOTE: pgcrypto is pre-installed in Supabase (extensions schema).
-- Creating extensions during seeding fails because the seed role lacks
-- pg_read_file permission needed by Supabase's extension hook scripts.
-- Extensions that need enabling should go in migrations, not seeds.
-- =============================================================================
