import { Factory } from "fishery";
import type { Tables } from "@trainers/supabase/types";

export const tournamentFactory = Factory.define<Tables<"tournaments">>(
  ({ sequence }) => ({
    id: sequence,
    name: `Tournament ${sequence}`,
    slug: `tournament-${sequence}`,
    organization_id: 1,
    allow_late_registration: false,
    archive_reason: null,
    archived_at: null,
    archived_by: null,
    battle_format: null,
    check_in_required: true,
    check_in_window_minutes: 15,
    created_at: new Date().toISOString(),
    current_phase_id: null,
    current_round: null,
    description: null,
    end_date: null,
    featured: false,
    format: null,
    game: "pokemon",
    game_format: null,
    late_check_in_max_round: null,
    max_participants: 32,
    open_team_sheets: false,
    participants: null,
    platform: null,
    prize_pool: null,
    registration_type: "open",
    rental_team_photos_enabled: false,
    rental_team_photos_required: false,
    round_time_minutes: 50,
    start_date: null,
    status: "draft",
    swiss_rounds: null,
    template_id: null,
    top_cut_size: null,
    tournament_format: "swiss",
    tournament_state: null,
    updated_at: new Date().toISOString(),
  })
);
