#!/bin/bash
# =============================================================================
# Postinstall Script - One-time local development setup
# =============================================================================
# Runs after `pnpm install` to set up:
#   1. .env.local with hardcoded Supabase demo keys + static ngrok domain
#   2. Symlinks from apps/packages to root .env.local
#   3. OAuth keys + JWKS for AT Protocol (Bluesky) auth
#
# This script is idempotent and skips work that's already done.
# It does NOT require Docker, ngrok, or any running services.
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[postinstall]${NC} $1"; }
log_success() { echo -e "${GREEN}[postinstall]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[postinstall]${NC} $1"; }
log_skip() { echo -e "${YELLOW}[postinstall]${NC} $1 (skipped)"; }

# =============================================================================
# Skip in CI/Production environments
# =============================================================================
if [ -n "$CI" ] || [ -n "$VERCEL" ] || [ -n "$NETLIFY" ] || [ -n "$GITHUB_ACTIONS" ] || [ -n "$RAILWAY_ENVIRONMENT" ]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.local"
ENV_NGROK="$ROOT_DIR/.env.ngrok"

# =============================================================================
# Supabase demo keys (placeholders — setup-local.sh replaces with live keys)
# =============================================================================
# These are placeholder values so .env.local can be created before Docker starts.
# `pnpm dev` runs setup-local.sh which replaces them with the actual keys from
# the running Supabase instance (which may use ES256 instead of HS256).
SUPABASE_ANON_KEY="placeholder-will-be-replaced-by-setup"
SUPABASE_SERVICE_ROLE_KEY="placeholder-will-be-replaced-by-setup"

# =============================================================================
# Step 1: Create .env.local (only if it doesn't exist)
# =============================================================================
create_env_file() {
  if [ -f "$ENV_FILE" ]; then
    log_skip ".env.local already exists"
    return 0
  fi

  log_info "Creating .env.local..."

  # Detect local IP for mobile development
  LOCAL_IP=""
  if command -v ipconfig &> /dev/null; then
    LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")
  fi
  if [ -z "$LOCAL_IP" ]; then
    if command -v ifconfig &> /dev/null; then
      LOCAL_IP=$(ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    elif [ -x /sbin/ifconfig ]; then
      LOCAL_IP=$(/sbin/ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    fi
  fi
  if [ -z "$LOCAL_IP" ] && command -v hostname &> /dev/null; then
    LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")
  fi
  if [ -z "$LOCAL_IP" ]; then
    LOCAL_IP="127.0.0.1"
  fi

  # Read static ngrok domain if available
  NGROK_DOMAIN=""
  if [ -f "$ENV_NGROK" ]; then
    NGROK_DOMAIN=$(grep "^NGROK_STATIC_DOMAIN=" "$ENV_NGROK" 2>/dev/null | cut -d'=' -f2-)
  fi

  # Set site URL: ngrok domain if available, otherwise localhost
  if [ -n "$NGROK_DOMAIN" ]; then
    SITE_URL="https://$NGROK_DOMAIN"
  else
    SITE_URL="http://localhost:3000"
  fi

  cat > "$ENV_FILE" << EOF
# =============================================================================
# Local Development Environment (auto-generated by postinstall.sh)
# =============================================================================
# Single source of truth for all local env vars.
# Symlinked into apps/ and packages/ directories.
#
# To use a remote Supabase instance instead, replace the Supabase values with
# your project credentials from https://app.supabase.com/project/_/settings/api
# =============================================================================

# Web app (Next.js) - uses localhost for browser access
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Mobile app (Expo) - uses local IP for physical device access
# If testing on physical device, ensure your device is on the same network
EXPO_PUBLIC_SUPABASE_URL=http://$LOCAL_IP:54321
EXPO_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Server-side only (never expose to client)
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# =============================================================================
# AT Protocol / Bluesky OAuth
# =============================================================================
# ATPROTO_PRIVATE_KEY is auto-generated by postinstall.sh
# NEXT_PUBLIC_SITE_URL is your ngrok tunnel URL (set via .env.ngrok)
ATPROTO_PRIVATE_KEY=
NEXT_PUBLIC_SITE_URL=$SITE_URL

# =============================================================================
# PDS Configuration (used by Supabase config.toml and edge functions)
# =============================================================================
# For local dev, edge functions reach PDS via Docker networking.
# No ngrok tunnel needed for PDS itself.
PDS_HOST=http://host.docker.internal:3001
PDS_ADMIN_PASSWORD=localdevpassword
PDS_HANDLE_DOMAIN=localhost

# =============================================================================
# OAuth Provider Credentials (used by Supabase config.toml)
# =============================================================================
# Discord: https://discord.com/developers/applications
SUPABASE_AUTH_EXTERNAL_DISCORD_CLIENT_ID=
SUPABASE_AUTH_EXTERNAL_DISCORD_SECRET=
# GitHub: https://github.com/settings/developers
SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID=
SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET=
EOF

  log_success "Created .env.local"
}

# =============================================================================
# Step 2: Create symlinks (idempotent)
# =============================================================================
create_symlinks() {
  local created=0

  # App directories get .env.local symlinks
  local app_dirs=("$ROOT_DIR/apps/web" "$ROOT_DIR/apps/mobile")
  for app_dir in "${app_dirs[@]}"; do
    if [ -d "$app_dir" ]; then
      local target="$app_dir/.env.local"
      if [ -L "$target" ]; then
        continue  # symlink already exists
      fi
      if [ -f "$target" ]; then
        mv "$target" "$target.backup"
        log_warn "Backed up existing $target"
      fi
      cd "$app_dir"
      ln -s "../../.env.local" ".env.local"
      created=$((created + 1))
    fi
  done

  # Supabase directories get .env symlinks
  local supabase_targets=(
    "$ROOT_DIR/packages/supabase:.env:../../.env.local"
    "$ROOT_DIR/packages/supabase/supabase:.env:../../../.env.local"
    "$ROOT_DIR/packages/supabase/supabase/functions:.env:../../../../.env.local"
  )
  for entry in "${supabase_targets[@]}"; do
    IFS=':' read -r target_dir file_name rel_path <<< "$entry"
    if [ -d "$target_dir" ]; then
      local target="$target_dir/$file_name"
      if [ -L "$target" ]; then
        continue  # symlink already exists
      fi
      if [ -f "$target" ]; then
        mv "$target" "$target.backup"
        log_warn "Backed up existing $target"
      fi
      cd "$target_dir"
      ln -s "$rel_path" "$file_name"
      created=$((created + 1))
    fi
  done

  if [ "$created" -gt 0 ]; then
    log_success "Created $created symlinks"
  else
    log_skip "All symlinks already exist"
  fi
}

# =============================================================================
# Step 3: Generate OAuth keys + JWKS (if not present)
# =============================================================================
generate_oauth_keys() {
  local jwks_file="$ROOT_DIR/apps/web/public/oauth/jwks.json"

  # Skip if both JWKS and private key already exist
  if [ -f "$jwks_file" ] && grep -q 'ATPROTO_PRIVATE_KEY=.\+' "$ENV_FILE" 2>/dev/null; then
    log_skip "OAuth keys already configured"
    return 0
  fi

  if ! command -v node &>/dev/null; then
    log_warn "Node.js not found, skipping OAuth key generation"
    return 0
  fi

  log_info "Generating OAuth keys..."
  (cd "$ROOT_DIR/apps/web" && node "$ROOT_DIR/apps/web/scripts/generate-oauth-keys.mjs")

  if [ $? -eq 0 ]; then
    log_success "OAuth keys generated"
  else
    log_warn "OAuth key generation failed (non-fatal)"
    log_warn "Bluesky login will not work until OAuth is configured"
  fi
}

# =============================================================================
# Main
# =============================================================================
main() {
  log_info "Running postinstall setup..."

  create_env_file
  create_symlinks
  generate_oauth_keys

  log_success "Postinstall complete"
}

main "$@"
