/**
 * Supabase Database Types
 *
 * This file will be auto-generated by running:
 *   pnpm generate-types
 *
 * For now, we provide a placeholder type structure.
 * Once you set up your Supabase project and run migrations,
 * regenerate this file to get full type safety.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Placeholder database types.
 * Run `pnpm generate-types` after setting up your Supabase project
 * to replace this with actual generated types.
 */
export interface Database {
  public: {
    Tables: {
      // Placeholder - will be populated by supabase gen types
      _placeholder: {
        Row: Record<string, never>;
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

/**
 * Helper type to extract table row types
 */
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

/**
 * Helper type to extract table insert types
 */
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

/**
 * Helper type to extract table update types
 */
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

/**
 * Helper type to extract enum types
 */
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
